#
# Glean Client API
# # Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 
# Version: 0.9.0
# Contact: support@glean.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'AnnouncementsApi' {
    Context 'New-announcement' {
        It 'Test New-announcement' {
            #$TestResult = New-announcement -Payload "TEST_VALUE" -XScioActas "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'New-draftannouncement' {
        It 'Test New-draftannouncement' {
            #$TestResult = New-draftannouncement -Payload "TEST_VALUE" -XScioActas "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-Deleteannouncement' {
        It 'Test Invoke-Deleteannouncement' {
            #$TestResult = Invoke-Deleteannouncement -Payload "TEST_VALUE" -XScioActas "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-Deletedraftannouncement' {
        It 'Test Invoke-Deletedraftannouncement' {
            #$TestResult = Invoke-Deletedraftannouncement -Payload "TEST_VALUE" -XScioActas "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-announcement' {
        It 'Test Get-announcement' {
            #$TestResult = Get-announcement -Payload "TEST_VALUE" -XScioActas "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-draftannouncement' {
        It 'Test Get-draftannouncement' {
            #$TestResult = Get-draftannouncement -Payload "TEST_VALUE" -XScioActas "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-Listannouncements' {
        It 'Test Invoke-Listannouncements' {
            #$TestResult = Invoke-Listannouncements -Payload "TEST_VALUE" -XScioActas "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-Previewannouncement' {
        It 'Test Invoke-Previewannouncement' {
            #$TestResult = Invoke-Previewannouncement -Payload "TEST_VALUE" -XScioActas "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-Previewannouncementdraft' {
        It 'Test Invoke-Previewannouncementdraft' {
            #$TestResult = Invoke-Previewannouncementdraft -Payload "TEST_VALUE" -XScioActas "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Publish-draftannouncement' {
        It 'Test Publish-draftannouncement' {
            #$TestResult = Publish-draftannouncement -Payload "TEST_VALUE" -XScioActas "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Unpublish-announcement' {
        It 'Test Unpublish-announcement' {
            #$TestResult = Unpublish-announcement -Payload "TEST_VALUE" -XScioActas "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Update-announcement' {
        It 'Test Update-announcement' {
            #$TestResult = Update-announcement -Payload "TEST_VALUE" -XScioActas "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Update-draftannouncement' {
        It 'Test Update-draftannouncement' {
            #$TestResult = Update-draftannouncement -Payload "TEST_VALUE" -XScioActas "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
