#
# Glean Client API
# # Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 
# Version: 0.9.0
# Contact: support@glean.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'SearchApi' {
    Context 'Invoke-Adminsearch' {
        It 'Test Invoke-Adminsearch' {
            #$TestResult = Invoke-Adminsearch -XScioActas "TEST_VALUE" -Payload "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-Autocomplete' {
        It 'Test Invoke-Autocomplete' {
            #$TestResult = Invoke-Autocomplete -Payload "TEST_VALUE" -XScioActas "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-Feed' {
        It 'Test Invoke-Feed' {
            #$TestResult = Invoke-Feed -Payload "TEST_VALUE" -XScioActas "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-Peoplesuggest' {
        It 'Test Invoke-Peoplesuggest' {
            #$TestResult = Invoke-Peoplesuggest -Payload "TEST_VALUE" -XScioActas "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-Peoplesuggestadmin' {
        It 'Test Invoke-Peoplesuggestadmin' {
            #$TestResult = Invoke-Peoplesuggestadmin -Payload "TEST_VALUE" -XScioActas "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-Recommendations' {
        It 'Test Invoke-Recommendations' {
            #$TestResult = Invoke-Recommendations -XScioActas "TEST_VALUE" -Payload "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Search-' {
        It 'Test Search-' {
            #$TestResult = Search- -XScioActas "TEST_VALUE" -Payload "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
