"""
    Glean Indexing API

    # Introduction In addition to the data sources that Glean has built-in support for, Glean also provides a REST API that enables customers to put arbitrary content in the search index. This is useful, for example, for doing permissions-aware search over content in internal tools that reside on-prem as well as for searching over applications that Glean does not currently support first class. In addition these APIs allow the customer to push organization data (people info, organization structure etc) into Glean.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.   # noqa: E501

    The version of the OpenAPI document: 0.9.0
    Contact: support@glean.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import glean_indexing_api_client
from glean_indexing_api_client.api.debug_api import DebugApi  # noqa: E501


class TestDebugApi(unittest.TestCase):
    """DebugApi unit test stubs"""

    def setUp(self):
        self.api = DebugApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_debug_datasource_status_get(self):
        """Test case for debug_datasource_status_get

        Get debug status  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
