"""
    Glean Indexing API

    # Introduction In addition to the data sources that Glean has built-in support for, Glean also provides a REST API that enables customers to put arbitrary content in the search index. This is useful, for example, for doing permissions-aware search over content in internal tools that reside on-prem as well as for searching over applications that Glean does not currently support first class. In addition these APIs allow the customer to push organization data (people info, organization structure etc) into Glean.  # Early Access Please note that we are continually evolving the system so these APIs are considered “early access” and are subject to change.   # noqa: E501

    The version of the OpenAPI document: 0.9.0
    Contact: support@glean.com
    Generated by: https://openapi-generator.tech
"""

import unittest

from glean_indexing_api_client.model.canonicalizing_regex_type import \
    CanonicalizingRegexType
from glean_indexing_api_client.model.connector_type import ConnectorType
from glean_indexing_api_client.model.object_definition import ObjectDefinition
from glean_indexing_api_client.model.quicklink import Quicklink

globals()['CanonicalizingRegexType'] = CanonicalizingRegexType
globals()['ConnectorType'] = ConnectorType
globals()['ObjectDefinition'] = ObjectDefinition
globals()['Quicklink'] = Quicklink


class TestSharedDatasourceConfigNoInstance(unittest.TestCase):
    """SharedDatasourceConfigNoInstance unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSharedDatasourceConfigNoInstance(self):
        """Test SharedDatasourceConfigNoInstance"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SharedDatasourceConfigNoInstance()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
