"""
    Glean Indexing API

    # Introduction In addition to the data sources that Glean has built-in support for, Glean also provides a REST API that enables customers to put arbitrary content in the search index. This is useful, for example, for doing permissions-aware search over content in internal tools that reside on-prem as well as for searching over applications that Glean does not currently support first class. In addition these APIs allow the customer to push organization data (people info, organization structure etc) into Glean.  # Early Access Please note that we are continually evolving the system so these APIs are considered “early access” and are subject to change.   # noqa: E501

    The version of the OpenAPI document: 0.9.0
    Contact: support@glean.com
    Generated by: https://openapi-generator.tech
"""

import sys
import unittest

import glean_indexing_api_client
from glean_indexing_api_client.model.additional_field_definition import AdditionalFieldDefinition
from glean_indexing_api_client.model.datasource_profile import DatasourceProfile
from glean_indexing_api_client.model.employee_team_info import EmployeeTeamInfo
from glean_indexing_api_client.model.social_network_definition import SocialNetworkDefinition
from glean_indexing_api_client.model.structured_location import StructuredLocation

globals()['AdditionalFieldDefinition'] = AdditionalFieldDefinition
globals()['DatasourceProfile'] = DatasourceProfile
globals()['EmployeeTeamInfo'] = EmployeeTeamInfo
globals()['SocialNetworkDefinition'] = SocialNetworkDefinition
globals()['StructuredLocation'] = StructuredLocation
from glean_indexing_api_client.model.employee_info_definition import EmployeeInfoDefinition


class TestEmployeeInfoDefinition(unittest.TestCase):
    """EmployeeInfoDefinition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEmployeeInfoDefinition(self):
        """Test EmployeeInfoDefinition"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EmployeeInfoDefinition()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
