"""
    Glean Indexing API

    # Introduction In addition to the data sources that Glean has built-in support for, Glean also provides a REST API that enables customers to put arbitrary content in the search index. This is useful, for example, for doing permissions-aware search over content in internal tools that reside on-prem as well as for searching over applications that Glean does not currently support first class. In addition these APIs allow the customer to push organization data (people info, organization structure etc) into Glean.  # Early Access Please note that we are continually evolving the system so these APIs are considered “early access” and are subject to change.   # noqa: E501

    The version of the OpenAPI document: 0.9.0
    Contact: support@glean.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import glean_indexing_api_client
from glean_indexing_api_client.model.int import Int
globals()['Int'] = Int
from glean_indexing_api_client.model.get_user_count_response import GetUserCountResponse


class TestGetUserCountResponse(unittest.TestCase):
    """GetUserCountResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetUserCountResponse(self):
        """Test GetUserCountResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetUserCountResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
