#
# Glean Client API
# # Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 
# Version: 0.9.0
# Contact: support@glean.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER CollectionId
The ID of the Collection to add items to.
.PARAMETER AddedCollectionItemDescriptors
The CollectionItemDescriptors of the items being added.
.OUTPUTS

AddCollectionItemsRequest<PSCustomObject>
#>

function Initialize-AddCollectionItemsRequest {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [Decimal]
        ${CollectionId},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${AddedCollectionItemDescriptors}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => AddCollectionItemsRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $CollectionId) {
            throw "invalid value for 'CollectionId', 'CollectionId' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "collectionId" = ${CollectionId}
            "addedCollectionItemDescriptors" = ${AddedCollectionItemDescriptors}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to AddCollectionItemsRequest<PSCustomObject>

.DESCRIPTION

Convert from JSON to AddCollectionItemsRequest<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

AddCollectionItemsRequest<PSCustomObject>
#>
function ConvertFrom-JsonToAddCollectionItemsRequest {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => AddCollectionItemsRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in AddCollectionItemsRequest
        $AllProperties = ("collectionId", "addedCollectionItemDescriptors")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'collectionId' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "collectionId"))) {
            throw "Error! JSON cannot be serialized due to the required property 'collectionId' missing."
        } else {
            $CollectionId = $JsonParameters.PSobject.Properties["collectionId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "addedCollectionItemDescriptors"))) { #optional property not found
            $AddedCollectionItemDescriptors = $null
        } else {
            $AddedCollectionItemDescriptors = $JsonParameters.PSobject.Properties["addedCollectionItemDescriptors"].value
        }

        $PSO = [PSCustomObject]@{
            "collectionId" = ${CollectionId}
            "addedCollectionItemDescriptors" = ${AddedCollectionItemDescriptors}
        }

        return $PSO
    }

}

