#
# Glean Client API
# # Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 
# Version: 0.9.0
# Contact: support@glean.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Admin alert related information that is used to construct the admin alert email

.PARAMETER Name
The name of the admin alert
.PARAMETER TriggeredTime
The time that the alert was triggered
.PARAMETER ProjectName
Human readable name of the project instance
.PARAMETER HelpLink
Help link for the alert that the admin can reference
.PARAMETER Datasource
Datasource that the alert is related to (possibly null)
.PARAMETER BannerType
Banner type to display for this alert
.PARAMETER BannerText
Text to display for the alert banner
.PARAMETER AlertDescription
Text for what happened section of an admin alert.
.PARAMETER RelevanceDescription
Text for why this matters section of an admin alert.
.PARAMETER ResolutionStepsDescription
Text for to do section before actual steps.
.PARAMETER ResolutionSteps
Steps to take to resolve an alert which are optionally mapped to a link for instructions (e.g. help doc)
.PARAMETER InstanceDisplayName
datasource instance's user set display name
.PARAMETER InstanceName
datsource instance's name e.g. confluence_0a0odwv
.OUTPUTS

AlertData<PSCustomObject>
#>

function Initialize-AlertData {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Name},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[System.DateTime]]
        ${TriggeredTime},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ProjectName},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${HelpLink},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Datasource},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("ACTION_REQUIRED", "REVIEW_REQUIRED")]
        [String]
        ${BannerType},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${BannerText},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${AlertDescription},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${RelevanceDescription},
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ResolutionStepsDescription},
        [Parameter(Position = 10, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${ResolutionSteps},
        [Parameter(Position = 11, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${InstanceDisplayName},
        [Parameter(Position = 12, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${InstanceName}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => AlertData' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "name" = ${Name}
            "triggeredTime" = ${TriggeredTime}
            "projectName" = ${ProjectName}
            "helpLink" = ${HelpLink}
            "datasource" = ${Datasource}
            "bannerType" = ${BannerType}
            "bannerText" = ${BannerText}
            "alertDescription" = ${AlertDescription}
            "relevanceDescription" = ${RelevanceDescription}
            "resolutionStepsDescription" = ${ResolutionStepsDescription}
            "resolutionSteps" = ${ResolutionSteps}
            "instanceDisplayName" = ${InstanceDisplayName}
            "instanceName" = ${InstanceName}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to AlertData<PSCustomObject>

.DESCRIPTION

Convert from JSON to AlertData<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

AlertData<PSCustomObject>
#>
function ConvertFrom-JsonToAlertData {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => AlertData' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in AlertData
        $AllProperties = ("name", "triggeredTime", "projectName", "helpLink", "datasource", "bannerType", "bannerText", "alertDescription", "relevanceDescription", "resolutionStepsDescription", "resolutionSteps", "instanceDisplayName", "instanceName")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "name"))) { #optional property not found
            $Name = $null
        } else {
            $Name = $JsonParameters.PSobject.Properties["name"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "triggeredTime"))) { #optional property not found
            $TriggeredTime = $null
        } else {
            $TriggeredTime = $JsonParameters.PSobject.Properties["triggeredTime"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "projectName"))) { #optional property not found
            $ProjectName = $null
        } else {
            $ProjectName = $JsonParameters.PSobject.Properties["projectName"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "helpLink"))) { #optional property not found
            $HelpLink = $null
        } else {
            $HelpLink = $JsonParameters.PSobject.Properties["helpLink"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "datasource"))) { #optional property not found
            $Datasource = $null
        } else {
            $Datasource = $JsonParameters.PSobject.Properties["datasource"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "bannerType"))) { #optional property not found
            $BannerType = $null
        } else {
            $BannerType = $JsonParameters.PSobject.Properties["bannerType"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "bannerText"))) { #optional property not found
            $BannerText = $null
        } else {
            $BannerText = $JsonParameters.PSobject.Properties["bannerText"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "alertDescription"))) { #optional property not found
            $AlertDescription = $null
        } else {
            $AlertDescription = $JsonParameters.PSobject.Properties["alertDescription"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "relevanceDescription"))) { #optional property not found
            $RelevanceDescription = $null
        } else {
            $RelevanceDescription = $JsonParameters.PSobject.Properties["relevanceDescription"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "resolutionStepsDescription"))) { #optional property not found
            $ResolutionStepsDescription = $null
        } else {
            $ResolutionStepsDescription = $JsonParameters.PSobject.Properties["resolutionStepsDescription"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "resolutionSteps"))) { #optional property not found
            $ResolutionSteps = $null
        } else {
            $ResolutionSteps = $JsonParameters.PSobject.Properties["resolutionSteps"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "instanceDisplayName"))) { #optional property not found
            $InstanceDisplayName = $null
        } else {
            $InstanceDisplayName = $JsonParameters.PSobject.Properties["instanceDisplayName"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "instanceName"))) { #optional property not found
            $InstanceName = $null
        } else {
            $InstanceName = $JsonParameters.PSobject.Properties["instanceName"].value
        }

        $PSO = [PSCustomObject]@{
            "name" = ${Name}
            "triggeredTime" = ${TriggeredTime}
            "projectName" = ${ProjectName}
            "helpLink" = ${HelpLink}
            "datasource" = ${Datasource}
            "bannerType" = ${BannerType}
            "bannerText" = ${BannerText}
            "alertDescription" = ${AlertDescription}
            "relevanceDescription" = ${RelevanceDescription}
            "resolutionStepsDescription" = ${ResolutionStepsDescription}
            "resolutionSteps" = ${ResolutionSteps}
            "instanceDisplayName" = ${InstanceDisplayName}
            "instanceName" = ${InstanceName}
        }

        return $PSO
    }

}

