#
# Glean Client API
# # Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 
# Version: 0.9.0
# Contact: support@glean.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER StartTime
The date and time at which the announcement becomes active.
.PARAMETER EndTime
The date and time at which the announcement expires.
.PARAMETER Title
The headline of the announcement.
.PARAMETER Body
No description available.
.PARAMETER Emoji
An emoji used to indicate the nature of the announcement.
.PARAMETER Thumbnail
No description available.
.PARAMETER Banner
No description available.
.PARAMETER AudienceFilters
Filters which restrict who should see the announcement. Values are taken from the corresponding filters in people search.
.PARAMETER SourceDocumentId
The Glean Document ID of the source document this Announcement was created from (e.g. Slack thread).
.PARAMETER HideAttribution
Whether or not to hide an author attribution.
.PARAMETER Channel
This determines whether this is a Social Feed post or a regular announcement.
.PARAMETER PostType
This determines whether this is an external-link post or a regular announcement post. TEXT - Regular announcement that can contain rich text. LINK - Announcement that is linked to an external site.
.PARAMETER IsPrioritized
Used by the Social Feed to pin posts to the front of the feed.
.PARAMETER ViewUrl
URL for viewing the announcement. It will be set to document URL for announcements from other datasources e.g. simpplr. Can only be written when channel=""SOCIAL_FEED"".
.PARAMETER DraftId
The opaque id of the associated draft.
.PARAMETER Permissions
No description available.
.PARAMETER Id
The opaque id of the announcement.
.PARAMETER Author
No description available.
.PARAMETER CreateTimestamp
Server Unix timestamp of the creation time (in seconds since epoch UTC).
.PARAMETER LastUpdateTimestamp
Server Unix timestamp of the last update time (in seconds since epoch UTC).
.PARAMETER UpdatedBy
No description available.
.PARAMETER ViewerInfo
No description available.
.PARAMETER SourceDocument
No description available.
.PARAMETER IsPublished
Whether or not the announcement is published.
.OUTPUTS

Announcement<PSCustomObject>
#>

function Initialize-Announcement {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[System.DateTime]]
        ${StartTime},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[System.DateTime]]
        ${EndTime},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Title},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Body},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Emoji},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Thumbnail},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Banner},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${AudienceFilters},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${SourceDocumentId},
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${HideAttribution},
        [Parameter(Position = 10, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("MAIN", "SOCIAL_FEED")]
        [String]
        ${Channel},
        [Parameter(Position = 11, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("TEXT", "LINK")]
        [String]
        ${PostType},
        [Parameter(Position = 12, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${IsPrioritized},
        [Parameter(Position = 13, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ViewUrl},
        [Parameter(Position = 14, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${DraftId},
        [Parameter(Position = 15, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Permissions},
        [Parameter(Position = 16, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Id},
        [Parameter(Position = 17, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Author},
        [Parameter(Position = 18, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${CreateTimestamp},
        [Parameter(Position = 19, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${LastUpdateTimestamp},
        [Parameter(Position = 20, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${UpdatedBy},
        [Parameter(Position = 21, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${ViewerInfo},
        [Parameter(Position = 22, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${SourceDocument},
        [Parameter(Position = 23, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${IsPublished}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => Announcement' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "startTime" = ${StartTime}
            "endTime" = ${EndTime}
            "title" = ${Title}
            "body" = ${Body}
            "emoji" = ${Emoji}
            "thumbnail" = ${Thumbnail}
            "banner" = ${Banner}
            "audienceFilters" = ${AudienceFilters}
            "sourceDocumentId" = ${SourceDocumentId}
            "hideAttribution" = ${HideAttribution}
            "channel" = ${Channel}
            "postType" = ${PostType}
            "isPrioritized" = ${IsPrioritized}
            "viewUrl" = ${ViewUrl}
            "draftId" = ${DraftId}
            "permissions" = ${Permissions}
            "id" = ${Id}
            "author" = ${Author}
            "createTimestamp" = ${CreateTimestamp}
            "lastUpdateTimestamp" = ${LastUpdateTimestamp}
            "updatedBy" = ${UpdatedBy}
            "viewerInfo" = ${ViewerInfo}
            "sourceDocument" = ${SourceDocument}
            "isPublished" = ${IsPublished}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to Announcement<PSCustomObject>

.DESCRIPTION

Convert from JSON to Announcement<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

Announcement<PSCustomObject>
#>
function ConvertFrom-JsonToAnnouncement {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => Announcement' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in Announcement
        $AllProperties = ("startTime", "endTime", "title", "body", "emoji", "thumbnail", "banner", "audienceFilters", "sourceDocumentId", "hideAttribution", "channel", "postType", "isPrioritized", "viewUrl", "draftId", "permissions", "id", "author", "createTimestamp", "lastUpdateTimestamp", "updatedBy", "viewerInfo", "sourceDocument", "isPublished")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "startTime"))) { #optional property not found
            $StartTime = $null
        } else {
            $StartTime = $JsonParameters.PSobject.Properties["startTime"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "endTime"))) { #optional property not found
            $EndTime = $null
        } else {
            $EndTime = $JsonParameters.PSobject.Properties["endTime"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "title"))) { #optional property not found
            $Title = $null
        } else {
            $Title = $JsonParameters.PSobject.Properties["title"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "body"))) { #optional property not found
            $Body = $null
        } else {
            $Body = $JsonParameters.PSobject.Properties["body"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "emoji"))) { #optional property not found
            $Emoji = $null
        } else {
            $Emoji = $JsonParameters.PSobject.Properties["emoji"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "thumbnail"))) { #optional property not found
            $Thumbnail = $null
        } else {
            $Thumbnail = $JsonParameters.PSobject.Properties["thumbnail"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "banner"))) { #optional property not found
            $Banner = $null
        } else {
            $Banner = $JsonParameters.PSobject.Properties["banner"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "audienceFilters"))) { #optional property not found
            $AudienceFilters = $null
        } else {
            $AudienceFilters = $JsonParameters.PSobject.Properties["audienceFilters"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "sourceDocumentId"))) { #optional property not found
            $SourceDocumentId = $null
        } else {
            $SourceDocumentId = $JsonParameters.PSobject.Properties["sourceDocumentId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "hideAttribution"))) { #optional property not found
            $HideAttribution = $null
        } else {
            $HideAttribution = $JsonParameters.PSobject.Properties["hideAttribution"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "channel"))) { #optional property not found
            $Channel = $null
        } else {
            $Channel = $JsonParameters.PSobject.Properties["channel"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "postType"))) { #optional property not found
            $PostType = $null
        } else {
            $PostType = $JsonParameters.PSobject.Properties["postType"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "isPrioritized"))) { #optional property not found
            $IsPrioritized = $null
        } else {
            $IsPrioritized = $JsonParameters.PSobject.Properties["isPrioritized"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "viewUrl"))) { #optional property not found
            $ViewUrl = $null
        } else {
            $ViewUrl = $JsonParameters.PSobject.Properties["viewUrl"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "draftId"))) { #optional property not found
            $DraftId = $null
        } else {
            $DraftId = $JsonParameters.PSobject.Properties["draftId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "permissions"))) { #optional property not found
            $Permissions = $null
        } else {
            $Permissions = $JsonParameters.PSobject.Properties["permissions"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "id"))) { #optional property not found
            $Id = $null
        } else {
            $Id = $JsonParameters.PSobject.Properties["id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "author"))) { #optional property not found
            $Author = $null
        } else {
            $Author = $JsonParameters.PSobject.Properties["author"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "createTimestamp"))) { #optional property not found
            $CreateTimestamp = $null
        } else {
            $CreateTimestamp = $JsonParameters.PSobject.Properties["createTimestamp"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "lastUpdateTimestamp"))) { #optional property not found
            $LastUpdateTimestamp = $null
        } else {
            $LastUpdateTimestamp = $JsonParameters.PSobject.Properties["lastUpdateTimestamp"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "updatedBy"))) { #optional property not found
            $UpdatedBy = $null
        } else {
            $UpdatedBy = $JsonParameters.PSobject.Properties["updatedBy"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "viewerInfo"))) { #optional property not found
            $ViewerInfo = $null
        } else {
            $ViewerInfo = $JsonParameters.PSobject.Properties["viewerInfo"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "sourceDocument"))) { #optional property not found
            $SourceDocument = $null
        } else {
            $SourceDocument = $JsonParameters.PSobject.Properties["sourceDocument"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "isPublished"))) { #optional property not found
            $IsPublished = $null
        } else {
            $IsPublished = $JsonParameters.PSobject.Properties["isPublished"].value
        }

        $PSO = [PSCustomObject]@{
            "startTime" = ${StartTime}
            "endTime" = ${EndTime}
            "title" = ${Title}
            "body" = ${Body}
            "emoji" = ${Emoji}
            "thumbnail" = ${Thumbnail}
            "banner" = ${Banner}
            "audienceFilters" = ${AudienceFilters}
            "sourceDocumentId" = ${SourceDocumentId}
            "hideAttribution" = ${HideAttribution}
            "channel" = ${Channel}
            "postType" = ${PostType}
            "isPrioritized" = ${IsPrioritized}
            "viewUrl" = ${ViewUrl}
            "draftId" = ${DraftId}
            "permissions" = ${Permissions}
            "id" = ${Id}
            "author" = ${Author}
            "createTimestamp" = ${CreateTimestamp}
            "lastUpdateTimestamp" = ${LastUpdateTimestamp}
            "updatedBy" = ${UpdatedBy}
            "viewerInfo" = ${ViewerInfo}
            "sourceDocument" = ${SourceDocument}
            "isPublished" = ${IsPublished}
        }

        return $PSO
    }

}

