#
# Glean Client API
# # Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 
# Version: 0.9.0
# Contact: support@glean.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Id
The opaque ID of the Answer.
.PARAMETER DocId
Glean Document ID of the Answer. The Glean Document ID is supported for cases where the Answer ID isn't available. If both are available, using the Answer ID is preferred.
.PARAMETER Question
No description available.
.PARAMETER QuestionVariations
Additional ways of phrasing this question.
.PARAMETER BodyText
The plain text answer to the question.
.PARAMETER BoardId
The parent board ID of this Answer, or 0 if it's a floating Answer.
.PARAMETER AudienceFilters
Filters which restrict who should see the answer. Values are taken from the corresponding filters in people search.
.PARAMETER AddedRoles
A list of user roles for the answer added by the owner.
.PARAMETER RemovedRoles
A list of user roles for the answer removed by the owner.
.PARAMETER Roles
A list of roles for this answer explicitly granted by an owner, editor, or admin.
.PARAMETER SourceDocumentSpec
No description available.
.PARAMETER SourceType
No description available.
.PARAMETER Permissions
No description available.
.PARAMETER CombinedAnswerText
No description available.
.PARAMETER Likes
No description available.
.PARAMETER Author
No description available.
.PARAMETER CreateTime
The time the answer was created in ISO format (ISO 8601).
.PARAMETER UpdateTime
The time the answer was last updated in ISO format (ISO 8601).
.PARAMETER UpdatedBy
No description available.
.PARAMETER Verification
No description available.
.PARAMETER Board
No description available.
.PARAMETER Collections
The collections to which the answer belongs.
.PARAMETER DocumentCategory
The document's document_category(.proto).
.PARAMETER SourceDocument
No description available.
.OUTPUTS

Answer<PSCustomObject>
#>

function Initialize-Answer {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [Int32]
        ${Id},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${DocId},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Question},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${QuestionVariations},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${BodyText},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${BoardId},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${AudienceFilters},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${AddedRoles},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${RemovedRoles},
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Roles},
        [Parameter(Position = 10, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${SourceDocumentSpec},
        [Parameter(Position = 11, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("DOCUMENT", "ASSISTANT")]
        [String]
        ${SourceType},
        [Parameter(Position = 12, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Permissions},
        [Parameter(Position = 13, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${CombinedAnswerText},
        [Parameter(Position = 14, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Likes},
        [Parameter(Position = 15, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Author},
        [Parameter(Position = 16, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[System.DateTime]]
        ${CreateTime},
        [Parameter(Position = 17, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[System.DateTime]]
        ${UpdateTime},
        [Parameter(Position = 18, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${UpdatedBy},
        [Parameter(Position = 19, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Verification},
        [Parameter(Position = 20, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Board},
        [Parameter(Position = 21, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Collections},
        [Parameter(Position = 22, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${DocumentCategory},
        [Parameter(Position = 23, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${SourceDocument}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => Answer' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $Id) {
            throw "invalid value for 'Id', 'Id' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "id" = ${Id}
            "docId" = ${DocId}
            "question" = ${Question}
            "questionVariations" = ${QuestionVariations}
            "bodyText" = ${BodyText}
            "boardId" = ${BoardId}
            "audienceFilters" = ${AudienceFilters}
            "addedRoles" = ${AddedRoles}
            "removedRoles" = ${RemovedRoles}
            "roles" = ${Roles}
            "sourceDocumentSpec" = ${SourceDocumentSpec}
            "sourceType" = ${SourceType}
            "permissions" = ${Permissions}
            "combinedAnswerText" = ${CombinedAnswerText}
            "likes" = ${Likes}
            "author" = ${Author}
            "createTime" = ${CreateTime}
            "updateTime" = ${UpdateTime}
            "updatedBy" = ${UpdatedBy}
            "verification" = ${Verification}
            "board" = ${Board}
            "collections" = ${Collections}
            "documentCategory" = ${DocumentCategory}
            "sourceDocument" = ${SourceDocument}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to Answer<PSCustomObject>

.DESCRIPTION

Convert from JSON to Answer<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

Answer<PSCustomObject>
#>
function ConvertFrom-JsonToAnswer {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => Answer' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in Answer
        $AllProperties = ("id", "docId", "question", "questionVariations", "bodyText", "boardId", "audienceFilters", "addedRoles", "removedRoles", "roles", "sourceDocumentSpec", "sourceType", "permissions", "combinedAnswerText", "likes", "author", "createTime", "updateTime", "updatedBy", "verification", "board", "collections", "documentCategory", "sourceDocument")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'id' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "id"))) {
            throw "Error! JSON cannot be serialized due to the required property 'id' missing."
        } else {
            $Id = $JsonParameters.PSobject.Properties["id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "docId"))) { #optional property not found
            $DocId = $null
        } else {
            $DocId = $JsonParameters.PSobject.Properties["docId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "question"))) { #optional property not found
            $Question = $null
        } else {
            $Question = $JsonParameters.PSobject.Properties["question"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "questionVariations"))) { #optional property not found
            $QuestionVariations = $null
        } else {
            $QuestionVariations = $JsonParameters.PSobject.Properties["questionVariations"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "bodyText"))) { #optional property not found
            $BodyText = $null
        } else {
            $BodyText = $JsonParameters.PSobject.Properties["bodyText"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "boardId"))) { #optional property not found
            $BoardId = $null
        } else {
            $BoardId = $JsonParameters.PSobject.Properties["boardId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "audienceFilters"))) { #optional property not found
            $AudienceFilters = $null
        } else {
            $AudienceFilters = $JsonParameters.PSobject.Properties["audienceFilters"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "addedRoles"))) { #optional property not found
            $AddedRoles = $null
        } else {
            $AddedRoles = $JsonParameters.PSobject.Properties["addedRoles"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "removedRoles"))) { #optional property not found
            $RemovedRoles = $null
        } else {
            $RemovedRoles = $JsonParameters.PSobject.Properties["removedRoles"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "roles"))) { #optional property not found
            $Roles = $null
        } else {
            $Roles = $JsonParameters.PSobject.Properties["roles"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "sourceDocumentSpec"))) { #optional property not found
            $SourceDocumentSpec = $null
        } else {
            $SourceDocumentSpec = $JsonParameters.PSobject.Properties["sourceDocumentSpec"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "sourceType"))) { #optional property not found
            $SourceType = $null
        } else {
            $SourceType = $JsonParameters.PSobject.Properties["sourceType"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "permissions"))) { #optional property not found
            $Permissions = $null
        } else {
            $Permissions = $JsonParameters.PSobject.Properties["permissions"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "combinedAnswerText"))) { #optional property not found
            $CombinedAnswerText = $null
        } else {
            $CombinedAnswerText = $JsonParameters.PSobject.Properties["combinedAnswerText"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "likes"))) { #optional property not found
            $Likes = $null
        } else {
            $Likes = $JsonParameters.PSobject.Properties["likes"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "author"))) { #optional property not found
            $Author = $null
        } else {
            $Author = $JsonParameters.PSobject.Properties["author"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "createTime"))) { #optional property not found
            $CreateTime = $null
        } else {
            $CreateTime = $JsonParameters.PSobject.Properties["createTime"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "updateTime"))) { #optional property not found
            $UpdateTime = $null
        } else {
            $UpdateTime = $JsonParameters.PSobject.Properties["updateTime"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "updatedBy"))) { #optional property not found
            $UpdatedBy = $null
        } else {
            $UpdatedBy = $JsonParameters.PSobject.Properties["updatedBy"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "verification"))) { #optional property not found
            $Verification = $null
        } else {
            $Verification = $JsonParameters.PSobject.Properties["verification"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "board"))) { #optional property not found
            $Board = $null
        } else {
            $Board = $JsonParameters.PSobject.Properties["board"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "collections"))) { #optional property not found
            $Collections = $null
        } else {
            $Collections = $JsonParameters.PSobject.Properties["collections"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "documentCategory"))) { #optional property not found
            $DocumentCategory = $null
        } else {
            $DocumentCategory = $JsonParameters.PSobject.Properties["documentCategory"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "sourceDocument"))) { #optional property not found
            $SourceDocument = $null
        } else {
            $SourceDocument = $JsonParameters.PSobject.Properties["sourceDocument"].value
        }

        $PSO = [PSCustomObject]@{
            "id" = ${Id}
            "docId" = ${DocId}
            "question" = ${Question}
            "questionVariations" = ${QuestionVariations}
            "bodyText" = ${BodyText}
            "boardId" = ${BoardId}
            "audienceFilters" = ${AudienceFilters}
            "addedRoles" = ${AddedRoles}
            "removedRoles" = ${RemovedRoles}
            "roles" = ${Roles}
            "sourceDocumentSpec" = ${SourceDocumentSpec}
            "sourceType" = ${SourceType}
            "permissions" = ${Permissions}
            "combinedAnswerText" = ${CombinedAnswerText}
            "likes" = ${Likes}
            "author" = ${Author}
            "createTime" = ${CreateTime}
            "updateTime" = ${UpdateTime}
            "updatedBy" = ${UpdatedBy}
            "verification" = ${Verification}
            "board" = ${Board}
            "collections" = ${Collections}
            "documentCategory" = ${DocumentCategory}
            "sourceDocument" = ${SourceDocument}
        }

        return $PSO
    }

}

