#
# Glean Client API
# # Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 
# Version: 0.9.0
# Contact: support@glean.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Question
No description available.
.PARAMETER QuestionVariations
Additional ways of phrasing this question.
.PARAMETER BodyText
The plain text answer to the question.
.PARAMETER BoardId
The parent board ID of this Answer, or 0 if it's a floating Answer.
.PARAMETER AudienceFilters
Filters which restrict who should see the answer. Values are taken from the corresponding filters in people search.
.PARAMETER AddedRoles
A list of user roles for the answer added by the owner.
.PARAMETER RemovedRoles
A list of user roles for the answer removed by the owner.
.PARAMETER Roles
A list of roles for this answer explicitly granted by an owner, editor, or admin.
.PARAMETER SourceDocumentSpec
No description available.
.PARAMETER SourceType
No description available.
.OUTPUTS

AnswerMutableProperties<PSCustomObject>
#>

function Initialize-AnswerMutableProperties {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Question},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${QuestionVariations},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${BodyText},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${BoardId},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${AudienceFilters},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${AddedRoles},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${RemovedRoles},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Roles},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${SourceDocumentSpec},
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("DOCUMENT", "ASSISTANT")]
        [String]
        ${SourceType}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => AnswerMutableProperties' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "question" = ${Question}
            "questionVariations" = ${QuestionVariations}
            "bodyText" = ${BodyText}
            "boardId" = ${BoardId}
            "audienceFilters" = ${AudienceFilters}
            "addedRoles" = ${AddedRoles}
            "removedRoles" = ${RemovedRoles}
            "roles" = ${Roles}
            "sourceDocumentSpec" = ${SourceDocumentSpec}
            "sourceType" = ${SourceType}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to AnswerMutableProperties<PSCustomObject>

.DESCRIPTION

Convert from JSON to AnswerMutableProperties<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

AnswerMutableProperties<PSCustomObject>
#>
function ConvertFrom-JsonToAnswerMutableProperties {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => AnswerMutableProperties' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in AnswerMutableProperties
        $AllProperties = ("question", "questionVariations", "bodyText", "boardId", "audienceFilters", "addedRoles", "removedRoles", "roles", "sourceDocumentSpec", "sourceType")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "question"))) { #optional property not found
            $Question = $null
        } else {
            $Question = $JsonParameters.PSobject.Properties["question"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "questionVariations"))) { #optional property not found
            $QuestionVariations = $null
        } else {
            $QuestionVariations = $JsonParameters.PSobject.Properties["questionVariations"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "bodyText"))) { #optional property not found
            $BodyText = $null
        } else {
            $BodyText = $JsonParameters.PSobject.Properties["bodyText"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "boardId"))) { #optional property not found
            $BoardId = $null
        } else {
            $BoardId = $JsonParameters.PSobject.Properties["boardId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "audienceFilters"))) { #optional property not found
            $AudienceFilters = $null
        } else {
            $AudienceFilters = $JsonParameters.PSobject.Properties["audienceFilters"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "addedRoles"))) { #optional property not found
            $AddedRoles = $null
        } else {
            $AddedRoles = $JsonParameters.PSobject.Properties["addedRoles"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "removedRoles"))) { #optional property not found
            $RemovedRoles = $null
        } else {
            $RemovedRoles = $JsonParameters.PSobject.Properties["removedRoles"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "roles"))) { #optional property not found
            $Roles = $null
        } else {
            $Roles = $JsonParameters.PSobject.Properties["roles"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "sourceDocumentSpec"))) { #optional property not found
            $SourceDocumentSpec = $null
        } else {
            $SourceDocumentSpec = $JsonParameters.PSobject.Properties["sourceDocumentSpec"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "sourceType"))) { #optional property not found
            $SourceType = $null
        } else {
            $SourceType = $JsonParameters.PSobject.Properties["sourceType"].value
        }

        $PSO = [PSCustomObject]@{
            "question" = ${Question}
            "questionVariations" = ${QuestionVariations}
            "bodyText" = ${BodyText}
            "boardId" = ${BoardId}
            "audienceFilters" = ${AudienceFilters}
            "addedRoles" = ${AddedRoles}
            "removedRoles" = ${RemovedRoles}
            "roles" = ${Roles}
            "sourceDocumentSpec" = ${SourceDocumentSpec}
            "sourceType" = ${SourceType}
        }

        return $PSO
    }

}

