#
# Glean Client API
# # Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 
# Version: 0.9.0
# Contact: support@glean.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Datasource
The app or other repository type this represents
.PARAMETER DocType
The datasource-specific type of the document (e.g. for Jira issues, this is the issue type such as Bug or Feature Request).
.PARAMETER MimeType
Mimetype is used to differentiate between sub applications from a datasource (e.g. Sheets, Docs from Gdrive)
.PARAMETER IconUrl
If there is available icon URL.
.OUTPUTS

AppResult<PSCustomObject>
#>

function Initialize-AppResult {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Datasource},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${DocType},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${MimeType},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${IconUrl}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => AppResult' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $Datasource) {
            throw "invalid value for 'Datasource', 'Datasource' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "datasource" = ${Datasource}
            "docType" = ${DocType}
            "mimeType" = ${MimeType}
            "iconUrl" = ${IconUrl}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to AppResult<PSCustomObject>

.DESCRIPTION

Convert from JSON to AppResult<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

AppResult<PSCustomObject>
#>
function ConvertFrom-JsonToAppResult {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => AppResult' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in AppResult
        $AllProperties = ("datasource", "docType", "mimeType", "iconUrl")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'datasource' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "datasource"))) {
            throw "Error! JSON cannot be serialized due to the required property 'datasource' missing."
        } else {
            $Datasource = $JsonParameters.PSobject.Properties["datasource"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "docType"))) { #optional property not found
            $DocType = $null
        } else {
            $DocType = $JsonParameters.PSobject.Properties["docType"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "mimeType"))) { #optional property not found
            $MimeType = $null
        } else {
            $MimeType = $JsonParameters.PSobject.Properties["mimeType"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "iconUrl"))) { #optional property not found
            $IconUrl = $null
        } else {
            $IconUrl = $JsonParameters.PSobject.Properties["iconUrl"].value
        }

        $PSO = [PSCustomObject]@{
            "datasource" = ${Datasource}
            "docType" = ${DocType}
            "mimeType" = ${MimeType}
            "iconUrl" = ${IconUrl}
        }

        return $PSO
    }

}

