#
# Glean Client API
# # Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 
# Version: 0.9.0
# Contact: support@glean.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER AccessToken
No description available.
.PARAMETER Datasource
No description available.
.PARAMETER Scope
No description available.
.PARAMETER TokenType
No description available.
.PARAMETER AuthUser
Used by Google to indicate the index of the logged in user. Useful for generating hyperlinks that support multilogin.
.PARAMETER Expiration
Unix timestamp when this token expires (in seconds since epoch UTC).
.OUTPUTS

AuthToken<PSCustomObject>
#>

function Initialize-AuthToken {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${AccessToken},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Datasource},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Scope},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${TokenType},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${AuthUser},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int64]]
        ${Expiration}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => AuthToken' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $AccessToken) {
            throw "invalid value for 'AccessToken', 'AccessToken' cannot be null."
        }

        if ($null -eq $Datasource) {
            throw "invalid value for 'Datasource', 'Datasource' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "accessToken" = ${AccessToken}
            "datasource" = ${Datasource}
            "scope" = ${Scope}
            "tokenType" = ${TokenType}
            "authUser" = ${AuthUser}
            "expiration" = ${Expiration}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to AuthToken<PSCustomObject>

.DESCRIPTION

Convert from JSON to AuthToken<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

AuthToken<PSCustomObject>
#>
function ConvertFrom-JsonToAuthToken {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => AuthToken' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in AuthToken
        $AllProperties = ("accessToken", "datasource", "scope", "tokenType", "authUser", "expiration")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'accessToken' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "accessToken"))) {
            throw "Error! JSON cannot be serialized due to the required property 'accessToken' missing."
        } else {
            $AccessToken = $JsonParameters.PSobject.Properties["accessToken"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "datasource"))) {
            throw "Error! JSON cannot be serialized due to the required property 'datasource' missing."
        } else {
            $Datasource = $JsonParameters.PSobject.Properties["datasource"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "scope"))) { #optional property not found
            $Scope = $null
        } else {
            $Scope = $JsonParameters.PSobject.Properties["scope"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "tokenType"))) { #optional property not found
            $TokenType = $null
        } else {
            $TokenType = $JsonParameters.PSobject.Properties["tokenType"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "authUser"))) { #optional property not found
            $AuthUser = $null
        } else {
            $AuthUser = $JsonParameters.PSobject.Properties["authUser"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "expiration"))) { #optional property not found
            $Expiration = $null
        } else {
            $Expiration = $JsonParameters.PSobject.Properties["expiration"].value
        }

        $PSO = [PSCustomObject]@{
            "accessToken" = ${AccessToken}
            "datasource" = ${Datasource}
            "scope" = ${Scope}
            "tokenType" = ${TokenType}
            "authUser" = ${AuthUser}
            "expiration" = ${Expiration}
        }

        return $PSO
    }

}

