#
# Glean Client API
# # Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 
# Version: 0.9.0
# Contact: support@glean.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER TrackingToken
No description available.
.PARAMETER SessionInfo
No description available.
.PARAMETER Query
Partially typed query.
.PARAMETER DatasourcesFilter
Filter results to only those relevant to one or more datasources (e.g. jira, gdrive). Results are unfiltered if missing.
.PARAMETER Datasource
Filter to only return results relevant to the given datasource.
.PARAMETER ResultTypes
Filter to only return results of the given type(s). All types may be returned if omitted.
.PARAMETER ResultSize
Maximum number of results to be returned. If no value is provided, the backend will cap at 200. 
.PARAMETER AuthTokens
Auth tokens which may be used for federated results.
.OUTPUTS

AutocompleteRequest<PSCustomObject>
#>

function Initialize-AutocompleteRequest {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${TrackingToken},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${SessionInfo},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Query},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${DatasourcesFilter},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Datasource},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("ADDITIONAL_DOCUMENT", "APP", "BROWSER_HISTORY", "DATASOURCE", "DOCUMENT", "ENTITY", "GOLINK", "HISTORY", "NEW_CHAT", "OPERATOR", "OPERATOR_VALUE", "QUICKLINK", "SUGGESTION")]
        [String[]]
        ${ResultTypes},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${ResultSize},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${AuthTokens}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => AutocompleteRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "trackingToken" = ${TrackingToken}
            "sessionInfo" = ${SessionInfo}
            "query" = ${Query}
            "datasourcesFilter" = ${DatasourcesFilter}
            "datasource" = ${Datasource}
            "resultTypes" = ${ResultTypes}
            "resultSize" = ${ResultSize}
            "authTokens" = ${AuthTokens}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to AutocompleteRequest<PSCustomObject>

.DESCRIPTION

Convert from JSON to AutocompleteRequest<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

AutocompleteRequest<PSCustomObject>
#>
function ConvertFrom-JsonToAutocompleteRequest {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => AutocompleteRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in AutocompleteRequest
        $AllProperties = ("trackingToken", "sessionInfo", "query", "datasourcesFilter", "datasource", "resultTypes", "resultSize", "authTokens")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "trackingToken"))) { #optional property not found
            $TrackingToken = $null
        } else {
            $TrackingToken = $JsonParameters.PSobject.Properties["trackingToken"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "sessionInfo"))) { #optional property not found
            $SessionInfo = $null
        } else {
            $SessionInfo = $JsonParameters.PSobject.Properties["sessionInfo"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "query"))) { #optional property not found
            $Query = $null
        } else {
            $Query = $JsonParameters.PSobject.Properties["query"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "datasourcesFilter"))) { #optional property not found
            $DatasourcesFilter = $null
        } else {
            $DatasourcesFilter = $JsonParameters.PSobject.Properties["datasourcesFilter"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "datasource"))) { #optional property not found
            $Datasource = $null
        } else {
            $Datasource = $JsonParameters.PSobject.Properties["datasource"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "resultTypes"))) { #optional property not found
            $ResultTypes = $null
        } else {
            $ResultTypes = $JsonParameters.PSobject.Properties["resultTypes"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "resultSize"))) { #optional property not found
            $ResultSize = $null
        } else {
            $ResultSize = $JsonParameters.PSobject.Properties["resultSize"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "authTokens"))) { #optional property not found
            $AuthTokens = $null
        } else {
            $AuthTokens = $JsonParameters.PSobject.Properties["authTokens"].value
        }

        $PSO = [PSCustomObject]@{
            "trackingToken" = ${TrackingToken}
            "sessionInfo" = ${SessionInfo}
            "query" = ${Query}
            "datasourcesFilter" = ${DatasourcesFilter}
            "datasource" = ${Datasource}
            "resultTypes" = ${ResultTypes}
            "resultSize" = ${ResultSize}
            "authTokens" = ${AuthTokens}
        }

        return $PSO
    }

}

