#
# Glean Client API
# # Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 
# Version: 0.9.0
# Contact: support@glean.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Displays a user's accomplishment or milestone

.PARAMETER Key
An auto generated unique identifier.
.PARAMETER DisplayName
The badge name displayed to users
.PARAMETER IconConfig
No description available.
.PARAMETER Pinned
The badge should be shown on the PersonAttribution
.OUTPUTS

Badge<PSCustomObject>
#>

function Initialize-Badge {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Key},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${DisplayName},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${IconConfig},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${Pinned}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => Badge' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "key" = ${Key}
            "displayName" = ${DisplayName}
            "iconConfig" = ${IconConfig}
            "pinned" = ${Pinned}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to Badge<PSCustomObject>

.DESCRIPTION

Convert from JSON to Badge<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

Badge<PSCustomObject>
#>
function ConvertFrom-JsonToBadge {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => Badge' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in Badge
        $AllProperties = ("key", "displayName", "iconConfig", "pinned")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "key"))) { #optional property not found
            $Key = $null
        } else {
            $Key = $JsonParameters.PSobject.Properties["key"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "displayName"))) { #optional property not found
            $DisplayName = $null
        } else {
            $DisplayName = $JsonParameters.PSobject.Properties["displayName"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "iconConfig"))) { #optional property not found
            $IconConfig = $null
        } else {
            $IconConfig = $JsonParameters.PSobject.Properties["iconConfig"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "pinned"))) { #optional property not found
            $Pinned = $null
        } else {
            $Pinned = $JsonParameters.PSobject.Properties["pinned"].value
        }

        $PSO = [PSCustomObject]@{
            "key" = ${Key}
            "displayName" = ${DisplayName}
            "iconConfig" = ${IconConfig}
            "pinned" = ${Pinned}
        }

        return $PSO
    }

}

