#
# Glean Client API
# # Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 
# Version: 0.9.0
# Contact: support@glean.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

A map of visual aspects of the app such as the company background image, logos, logo background colors, and wide company logos.

.PARAMETER CompanyBackgroundImageName
User facing company background image to be displayed to users on the home page.
.PARAMETER CompanyLogoUrl
An image URL pointing to a custom logo that should be displayed to users. Must be square and recognizable down to 40x40px. SVG images with transparent background are preferred.
.PARAMETER CompanyWideLogoUrl
An image URL pointing to a wide format custom logo that should be displayed to users. Should be rectangular and recognizable at 40px height, and aspect ratio should be between 2:1 and 4:1. SVG images with transparent background are preferred.
.PARAMETER CompanyLogoBackgroundColor
A hex RGB color to display behind custom logo (e.g. '#ff4080').
.OUTPUTS

Branding<PSCustomObject>
#>

function Initialize-Branding {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${CompanyBackgroundImageName},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${CompanyLogoUrl},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${CompanyWideLogoUrl},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${CompanyLogoBackgroundColor}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => Branding' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "companyBackgroundImageName" = ${CompanyBackgroundImageName}
            "companyLogoUrl" = ${CompanyLogoUrl}
            "companyWideLogoUrl" = ${CompanyWideLogoUrl}
            "companyLogoBackgroundColor" = ${CompanyLogoBackgroundColor}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to Branding<PSCustomObject>

.DESCRIPTION

Convert from JSON to Branding<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

Branding<PSCustomObject>
#>
function ConvertFrom-JsonToBranding {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => Branding' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in Branding
        $AllProperties = ("companyBackgroundImageName", "companyLogoUrl", "companyWideLogoUrl", "companyLogoBackgroundColor")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "companyBackgroundImageName"))) { #optional property not found
            $CompanyBackgroundImageName = $null
        } else {
            $CompanyBackgroundImageName = $JsonParameters.PSobject.Properties["companyBackgroundImageName"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "companyLogoUrl"))) { #optional property not found
            $CompanyLogoUrl = $null
        } else {
            $CompanyLogoUrl = $JsonParameters.PSobject.Properties["companyLogoUrl"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "companyWideLogoUrl"))) { #optional property not found
            $CompanyWideLogoUrl = $null
        } else {
            $CompanyWideLogoUrl = $JsonParameters.PSobject.Properties["companyWideLogoUrl"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "companyLogoBackgroundColor"))) { #optional property not found
            $CompanyLogoBackgroundColor = $null
        } else {
            $CompanyLogoBackgroundColor = $JsonParameters.PSobject.Properties["companyLogoBackgroundColor"].value
        }

        $PSO = [PSCustomObject]@{
            "companyBackgroundImageName" = ${CompanyBackgroundImageName}
            "companyLogoUrl" = ${CompanyLogoUrl}
            "companyWideLogoUrl" = ${CompanyWideLogoUrl}
            "companyLogoBackgroundColor" = ${CompanyLogoBackgroundColor}
        }

        return $PSO
    }

}

