#
# Glean Client API
# # Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 
# Version: 0.9.0
# Contact: support@glean.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Time
No description available.
.PARAMETER EventType
The nature of the event, for example ""out of office"".
.PARAMETER Id
The calendar event id
.PARAMETER Url
A permalink for this calendar event
.PARAMETER Attendees
No description available.
.PARAMETER Location
The location that this event is taking place at.
.PARAMETER ConferenceData
No description available.
.PARAMETER Description
The HTML description of the event.
.PARAMETER Datasource
The app or other repository type from which the event was extracted
.PARAMETER Classifications
No description available.
.PARAMETER GeneratedAttachments
No description available.
.OUTPUTS

CalendarEvent<PSCustomObject>
#>

function Initialize-CalendarEvent {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Time},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("DEFAULT", "OUT_OF_OFFICE")]
        [String]
        ${EventType},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Id},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Url},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Attendees},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Location},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${ConferenceData},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Description},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Datasource},
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Classifications},
        [Parameter(Position = 10, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${GeneratedAttachments}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => CalendarEvent' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $Id) {
            throw "invalid value for 'Id', 'Id' cannot be null."
        }

        if ($null -eq $Url) {
            throw "invalid value for 'Url', 'Url' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "time" = ${Time}
            "eventType" = ${EventType}
            "id" = ${Id}
            "url" = ${Url}
            "attendees" = ${Attendees}
            "location" = ${Location}
            "conferenceData" = ${ConferenceData}
            "description" = ${Description}
            "datasource" = ${Datasource}
            "classifications" = ${Classifications}
            "generatedAttachments" = ${GeneratedAttachments}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to CalendarEvent<PSCustomObject>

.DESCRIPTION

Convert from JSON to CalendarEvent<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

CalendarEvent<PSCustomObject>
#>
function ConvertFrom-JsonToCalendarEvent {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => CalendarEvent' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in CalendarEvent
        $AllProperties = ("time", "eventType", "id", "url", "attendees", "location", "conferenceData", "description", "datasource", "classifications", "generatedAttachments")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'id' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "id"))) {
            throw "Error! JSON cannot be serialized due to the required property 'id' missing."
        } else {
            $Id = $JsonParameters.PSobject.Properties["id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "url"))) {
            throw "Error! JSON cannot be serialized due to the required property 'url' missing."
        } else {
            $Url = $JsonParameters.PSobject.Properties["url"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "time"))) { #optional property not found
            $Time = $null
        } else {
            $Time = $JsonParameters.PSobject.Properties["time"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "eventType"))) { #optional property not found
            $EventType = $null
        } else {
            $EventType = $JsonParameters.PSobject.Properties["eventType"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "attendees"))) { #optional property not found
            $Attendees = $null
        } else {
            $Attendees = $JsonParameters.PSobject.Properties["attendees"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "location"))) { #optional property not found
            $Location = $null
        } else {
            $Location = $JsonParameters.PSobject.Properties["location"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "conferenceData"))) { #optional property not found
            $ConferenceData = $null
        } else {
            $ConferenceData = $JsonParameters.PSobject.Properties["conferenceData"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "description"))) { #optional property not found
            $Description = $null
        } else {
            $Description = $JsonParameters.PSobject.Properties["description"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "datasource"))) { #optional property not found
            $Datasource = $null
        } else {
            $Datasource = $JsonParameters.PSobject.Properties["datasource"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "classifications"))) { #optional property not found
            $Classifications = $null
        } else {
            $Classifications = $JsonParameters.PSobject.Properties["classifications"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "generatedAttachments"))) { #optional property not found
            $GeneratedAttachments = $null
        } else {
            $GeneratedAttachments = $JsonParameters.PSobject.Properties["generatedAttachments"].value
        }

        $PSO = [PSCustomObject]@{
            "time" = ${Time}
            "eventType" = ${EventType}
            "id" = ${Id}
            "url" = ${Url}
            "attendees" = ${Attendees}
            "location" = ${Location}
            "conferenceData" = ${ConferenceData}
            "description" = ${Description}
            "datasource" = ${Datasource}
            "classifications" = ${Classifications}
            "generatedAttachments" = ${GeneratedAttachments}
        }

        return $PSO
    }

}

