#
# Glean Client API
# # Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 
# Version: 0.9.0
# Contact: support@glean.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER People
Full details of some of the attendees of this event
.PARAMETER IsLimit
Whether the total count of the people returned is at the retrieval limit.
.PARAMETER Total
Total number of attendees in this event.
.PARAMETER NumAccepted
Total number of attendees who have accepted this event.
.PARAMETER NumDeclined
Total number of attendees who have declined this event.
.PARAMETER NumNoResponse
Total number of attendees who have not responded to this event.
.PARAMETER NumTentative
Total number of attendees who have responded tentatively (i.e. responded maybe) to this event.
.OUTPUTS

CalendarAttendees<PSCustomObject>
#>

function Initialize-CalendarAttendees {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${People},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${IsLimit},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Total},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${NumAccepted},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${NumDeclined},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${NumNoResponse},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${NumTentative}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => CalendarAttendees' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "people" = ${People}
            "isLimit" = ${IsLimit}
            "total" = ${Total}
            "numAccepted" = ${NumAccepted}
            "numDeclined" = ${NumDeclined}
            "numNoResponse" = ${NumNoResponse}
            "numTentative" = ${NumTentative}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to CalendarAttendees<PSCustomObject>

.DESCRIPTION

Convert from JSON to CalendarAttendees<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

CalendarAttendees<PSCustomObject>
#>
function ConvertFrom-JsonToCalendarAttendees {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => CalendarAttendees' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in CalendarAttendees
        $AllProperties = ("people", "isLimit", "total", "numAccepted", "numDeclined", "numNoResponse", "numTentative")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "people"))) { #optional property not found
            $People = $null
        } else {
            $People = $JsonParameters.PSobject.Properties["people"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "isLimit"))) { #optional property not found
            $IsLimit = $null
        } else {
            $IsLimit = $JsonParameters.PSobject.Properties["isLimit"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "total"))) { #optional property not found
            $Total = $null
        } else {
            $Total = $JsonParameters.PSobject.Properties["total"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "numAccepted"))) { #optional property not found
            $NumAccepted = $null
        } else {
            $NumAccepted = $JsonParameters.PSobject.Properties["numAccepted"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "numDeclined"))) { #optional property not found
            $NumDeclined = $null
        } else {
            $NumDeclined = $JsonParameters.PSobject.Properties["numDeclined"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "numNoResponse"))) { #optional property not found
            $NumNoResponse = $null
        } else {
            $NumNoResponse = $JsonParameters.PSobject.Properties["numNoResponse"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "numTentative"))) { #optional property not found
            $NumTentative = $null
        } else {
            $NumTentative = $JsonParameters.PSobject.Properties["numTentative"].value
        }

        $PSO = [PSCustomObject]@{
            "people" = ${People}
            "isLimit" = ${IsLimit}
            "total" = ${Total}
            "numAccepted" = ${NumAccepted}
            "numDeclined" = ${NumDeclined}
            "numNoResponse" = ${NumNoResponse}
            "numTentative" = ${NumTentative}
        }

        return $PSO
    }

}

