#
# Glean Client API
# # Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 
# Version: 0.9.0
# Contact: support@glean.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

A message that is rendered as one coherent unit with one given sender.

.PARAMETER AgentConfig
No description available.
.PARAMETER Author
No description available.
.PARAMETER Citations
A list of Citations used to generate the message.
.PARAMETER UploadedFileIds
IDs of files uploaded in the message that are referenced to generate the answer.
.PARAMETER Fragments
A list of chat results.
.PARAMETER Metadata
Metadata associated with the message (not displayed to the user but stored in the app).
.PARAMETER Ts
Timestamp of the message.
.PARAMETER MessageId
Unique ID of the message.
.PARAMETER MessageTrackingToken
Opaque tracking token generated server-side.
.PARAMETER MessageType
Used to determine the type of UI treatment to apply to this message.
.PARAMETER HasMoreFragments
Signals there are more fragments incoming.
.OUTPUTS

ChatMessage<PSCustomObject>
#>

function Initialize-ChatMessage {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${AgentConfig},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("USER", "GLEAN_AI")]
        [String]
        ${Author} = "USER",
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Citations},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${UploadedFileIds},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Fragments},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Metadata},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Ts},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${MessageId},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${MessageTrackingToken},
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("UPDATE", "CONTENT", "CONTEXT", "DEBUG", "DEBUG_EXTERNAL", "ERROR")]
        [String]
        ${MessageType},
        [Parameter(Position = 10, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${HasMoreFragments}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => ChatMessage' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "agentConfig" = ${AgentConfig}
            "author" = ${Author}
            "citations" = ${Citations}
            "uploadedFileIds" = ${UploadedFileIds}
            "fragments" = ${Fragments}
            "metadata" = ${Metadata}
            "ts" = ${Ts}
            "messageId" = ${MessageId}
            "messageTrackingToken" = ${MessageTrackingToken}
            "messageType" = ${MessageType}
            "hasMoreFragments" = ${HasMoreFragments}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ChatMessage<PSCustomObject>

.DESCRIPTION

Convert from JSON to ChatMessage<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ChatMessage<PSCustomObject>
#>
function ConvertFrom-JsonToChatMessage {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => ChatMessage' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in ChatMessage
        $AllProperties = ("agentConfig", "author", "citations", "uploadedFileIds", "fragments", "metadata", "ts", "messageId", "messageTrackingToken", "messageType", "hasMoreFragments")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "agentConfig"))) { #optional property not found
            $AgentConfig = $null
        } else {
            $AgentConfig = $JsonParameters.PSobject.Properties["agentConfig"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "author"))) { #optional property not found
            $Author = $null
        } else {
            $Author = $JsonParameters.PSobject.Properties["author"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "citations"))) { #optional property not found
            $Citations = $null
        } else {
            $Citations = $JsonParameters.PSobject.Properties["citations"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "uploadedFileIds"))) { #optional property not found
            $UploadedFileIds = $null
        } else {
            $UploadedFileIds = $JsonParameters.PSobject.Properties["uploadedFileIds"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "fragments"))) { #optional property not found
            $Fragments = $null
        } else {
            $Fragments = $JsonParameters.PSobject.Properties["fragments"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "metadata"))) { #optional property not found
            $Metadata = $null
        } else {
            $Metadata = $JsonParameters.PSobject.Properties["metadata"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "ts"))) { #optional property not found
            $Ts = $null
        } else {
            $Ts = $JsonParameters.PSobject.Properties["ts"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "messageId"))) { #optional property not found
            $MessageId = $null
        } else {
            $MessageId = $JsonParameters.PSobject.Properties["messageId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "messageTrackingToken"))) { #optional property not found
            $MessageTrackingToken = $null
        } else {
            $MessageTrackingToken = $JsonParameters.PSobject.Properties["messageTrackingToken"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "messageType"))) { #optional property not found
            $MessageType = $null
        } else {
            $MessageType = $JsonParameters.PSobject.Properties["messageType"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "hasMoreFragments"))) { #optional property not found
            $HasMoreFragments = $null
        } else {
            $HasMoreFragments = $JsonParameters.PSobject.Properties["hasMoreFragments"].value
        }

        $PSO = [PSCustomObject]@{
            "agentConfig" = ${AgentConfig}
            "author" = ${Author}
            "citations" = ${Citations}
            "uploadedFileIds" = ${UploadedFileIds}
            "fragments" = ${Fragments}
            "metadata" = ${Metadata}
            "ts" = ${Ts}
            "messageId" = ${MessageId}
            "messageTrackingToken" = ${MessageTrackingToken}
            "messageType" = ${MessageType}
            "hasMoreFragments" = ${HasMoreFragments}
        }

        return $PSO
    }

}

