#
# Glean Client API
# # Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 
# Version: 0.9.0
# Contact: support@glean.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

A single response from the /chat backend.

.PARAMETER Messages
No description available.
.PARAMETER ChatId
The id of the associated Chat the messages belong to, if one exists.
.PARAMETER FollowUpPrompts
Follow-up prompts for the user to potentially use
.PARAMETER BackendTimeMillis
Time in milliseconds the backend took to respond to the request.
.PARAMETER ChatSessionTrackingToken
A token that is used to track the session.
.OUTPUTS

ChatResponse<PSCustomObject>
#>

function Initialize-ChatResponse {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Messages},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ChatId},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${FollowUpPrompts},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int64]]
        ${BackendTimeMillis},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ChatSessionTrackingToken}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => ChatResponse' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "messages" = ${Messages}
            "chatId" = ${ChatId}
            "followUpPrompts" = ${FollowUpPrompts}
            "backendTimeMillis" = ${BackendTimeMillis}
            "chatSessionTrackingToken" = ${ChatSessionTrackingToken}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ChatResponse<PSCustomObject>

.DESCRIPTION

Convert from JSON to ChatResponse<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ChatResponse<PSCustomObject>
#>
function ConvertFrom-JsonToChatResponse {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => ChatResponse' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in ChatResponse
        $AllProperties = ("messages", "chatId", "followUpPrompts", "backendTimeMillis", "chatSessionTrackingToken")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "messages"))) { #optional property not found
            $Messages = $null
        } else {
            $Messages = $JsonParameters.PSobject.Properties["messages"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "chatId"))) { #optional property not found
            $ChatId = $null
        } else {
            $ChatId = $JsonParameters.PSobject.Properties["chatId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "followUpPrompts"))) { #optional property not found
            $FollowUpPrompts = $null
        } else {
            $FollowUpPrompts = $JsonParameters.PSobject.Properties["followUpPrompts"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "backendTimeMillis"))) { #optional property not found
            $BackendTimeMillis = $null
        } else {
            $BackendTimeMillis = $JsonParameters.PSobject.Properties["backendTimeMillis"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "chatSessionTrackingToken"))) { #optional property not found
            $ChatSessionTrackingToken = $null
        } else {
            $ChatSessionTrackingToken = $JsonParameters.PSobject.Properties["chatSessionTrackingToken"].value
        }

        $PSO = [PSCustomObject]@{
            "messages" = ${Messages}
            "chatId" = ${ChatId}
            "followUpPrompts" = ${FollowUpPrompts}
            "backendTimeMillis" = ${BackendTimeMillis}
            "chatSessionTrackingToken" = ${ChatSessionTrackingToken}
        }

        return $PSO
    }

}

