#
# Glean Client API
# # Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 
# Version: 0.9.0
# Contact: support@glean.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER ExistingPins
List of targets this Collection is pinned to.
.PARAMETER EligiblePins
List of targets this Collection can be pinned to, excluding the targets this Collection is already pinned to. We also include Collection ID already is pinned to each eligible target, which will be 0 if the target has no pinned Collection.
.OUTPUTS

CollectionPinnedMetadata<PSCustomObject>
#>

function Initialize-CollectionPinnedMetadata {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${ExistingPins},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${EligiblePins}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => CollectionPinnedMetadata' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "existingPins" = ${ExistingPins}
            "eligiblePins" = ${EligiblePins}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to CollectionPinnedMetadata<PSCustomObject>

.DESCRIPTION

Convert from JSON to CollectionPinnedMetadata<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

CollectionPinnedMetadata<PSCustomObject>
#>
function ConvertFrom-JsonToCollectionPinnedMetadata {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => CollectionPinnedMetadata' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in CollectionPinnedMetadata
        $AllProperties = ("existingPins", "eligiblePins")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "existingPins"))) { #optional property not found
            $ExistingPins = $null
        } else {
            $ExistingPins = $JsonParameters.PSobject.Properties["existingPins"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "eligiblePins"))) { #optional property not found
            $EligiblePins = $null
        } else {
            $EligiblePins = $JsonParameters.PSobject.Properties["eligiblePins"].value
        }

        $PSO = [PSCustomObject]@{
            "existingPins" = ${ExistingPins}
            "eligiblePins" = ${EligiblePins}
        }

        return $PSO
    }

}

