#
# Glean Client API
# # Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 
# Version: 0.9.0
# Contact: support@glean.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Label
A user-facing label for this field.
.PARAMETER Values
No description available.
.PARAMETER Displayable
Determines whether the client should display this custom field
.OUTPUTS

CustomFieldData<PSCustomObject>
#>

function Initialize-CustomFieldData {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Label},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Values},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [Boolean]
        ${Displayable} = $true
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => CustomFieldData' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $Label) {
            throw "invalid value for 'Label', 'Label' cannot be null."
        }

        if ($null -eq $Values) {
            throw "invalid value for 'Values', 'Values' cannot be null."
        }

        if ($null -eq $Displayable) {
            throw "invalid value for 'Displayable', 'Displayable' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "label" = ${Label}
            "values" = ${Values}
            "displayable" = ${Displayable}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to CustomFieldData<PSCustomObject>

.DESCRIPTION

Convert from JSON to CustomFieldData<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

CustomFieldData<PSCustomObject>
#>
function ConvertFrom-JsonToCustomFieldData {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => CustomFieldData' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in CustomFieldData
        $AllProperties = ("label", "values", "displayable")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'label' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "label"))) {
            throw "Error! JSON cannot be serialized due to the required property 'label' missing."
        } else {
            $Label = $JsonParameters.PSobject.Properties["label"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "values"))) {
            throw "Error! JSON cannot be serialized due to the required property 'values' missing."
        } else {
            $Values = $JsonParameters.PSobject.Properties["values"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "displayable"))) {
            throw "Error! JSON cannot be serialized due to the required property 'displayable' missing."
        } else {
            $Displayable = $JsonParameters.PSobject.Properties["displayable"].value
        }

        $PSO = [PSCustomObject]@{
            "label" = ${Label}
            "values" = ${Values}
            "displayable" = ${Displayable}
        }

        return $PSO
    }

}

