#
# Glean Client API
# # Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 
# Version: 0.9.0
# Contact: support@glean.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Id
The Glean Document ID.
.PARAMETER Datasource
The app or other repository type from which the document was extracted
.PARAMETER ConnectorType
No description available.
.PARAMETER DocType
The datasource-specific type of the document (e.g. for Jira issues, this is the issue type such as Bug or Feature Request).
.PARAMETER Content
No description available.
.PARAMETER ContainerDocument
No description available.
.PARAMETER ParentDocument
No description available.
.PARAMETER Title
The title of the document.
.PARAMETER Url
A permalink for the document.
.PARAMETER Metadata
No description available.
.PARAMETER Sections
A list of content sub-sections in the document, e.g. text blocks with different headings in a Drive doc or Confluence page.
.OUTPUTS

Document<PSCustomObject>
#>

function Initialize-Document {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Id},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Datasource},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("API_CRAWL", "BROWSER_CRAWL", "BROWSER_HISTORY", "BUILTIN", "FEDERATED_SEARCH", "PUSH_API", "WEB_CRAWL", "NATIVE_HISTORY")]
        [PSCustomObject]
        ${ConnectorType},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${DocType},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Content},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${ContainerDocument},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${ParentDocument},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Title},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Url},
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Metadata},
        [Parameter(Position = 10, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Sections}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => Document' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "id" = ${Id}
            "datasource" = ${Datasource}
            "connectorType" = ${ConnectorType}
            "docType" = ${DocType}
            "content" = ${Content}
            "containerDocument" = ${ContainerDocument}
            "parentDocument" = ${ParentDocument}
            "title" = ${Title}
            "url" = ${Url}
            "metadata" = ${Metadata}
            "sections" = ${Sections}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to Document<PSCustomObject>

.DESCRIPTION

Convert from JSON to Document<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

Document<PSCustomObject>
#>
function ConvertFrom-JsonToDocument {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => Document' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in Document
        $AllProperties = ("id", "datasource", "connectorType", "docType", "content", "containerDocument", "parentDocument", "title", "url", "metadata", "sections")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "id"))) { #optional property not found
            $Id = $null
        } else {
            $Id = $JsonParameters.PSobject.Properties["id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "datasource"))) { #optional property not found
            $Datasource = $null
        } else {
            $Datasource = $JsonParameters.PSobject.Properties["datasource"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "connectorType"))) { #optional property not found
            $ConnectorType = $null
        } else {
            $ConnectorType = $JsonParameters.PSobject.Properties["connectorType"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "docType"))) { #optional property not found
            $DocType = $null
        } else {
            $DocType = $JsonParameters.PSobject.Properties["docType"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "content"))) { #optional property not found
            $Content = $null
        } else {
            $Content = $JsonParameters.PSobject.Properties["content"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "containerDocument"))) { #optional property not found
            $ContainerDocument = $null
        } else {
            $ContainerDocument = $JsonParameters.PSobject.Properties["containerDocument"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "parentDocument"))) { #optional property not found
            $ParentDocument = $null
        } else {
            $ParentDocument = $JsonParameters.PSobject.Properties["parentDocument"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "title"))) { #optional property not found
            $Title = $null
        } else {
            $Title = $JsonParameters.PSobject.Properties["title"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "url"))) { #optional property not found
            $Url = $null
        } else {
            $Url = $JsonParameters.PSobject.Properties["url"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "metadata"))) { #optional property not found
            $Metadata = $null
        } else {
            $Metadata = $JsonParameters.PSobject.Properties["metadata"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "sections"))) { #optional property not found
            $Sections = $null
        } else {
            $Sections = $JsonParameters.PSobject.Properties["sections"].value
        }

        $PSO = [PSCustomObject]@{
            "id" = ${Id}
            "datasource" = ${Datasource}
            "connectorType" = ${ConnectorType}
            "docType" = ${DocType}
            "content" = ${Content}
            "containerDocument" = ${ContainerDocument}
            "parentDocument" = ${ParentDocument}
            "title" = ${Title}
            "url" = ${Url}
            "metadata" = ${Metadata}
            "sections" = ${Sections}
        }

        return $PSO
    }

}

