#
# Glean Client API
# # Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 
# Version: 0.9.0
# Contact: support@glean.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER CollectionId
The ID of the Collection to edit CollectionItems in.
.PARAMETER ItemId
The ID of the CollectionItem to edit.
.PARAMETER Name
The optional name of the Collection item.
.PARAMETER Description
A helpful description of why this CollectionItem is in the Collection that it's in.
.PARAMETER Icon
The emoji icon for this CollectionItem. Only used for Text type items.
.OUTPUTS

EditCollectionItemRequest<PSCustomObject>
#>

function Initialize-EditCollectionItemRequest {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [Int32]
        ${CollectionId},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ItemId},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Name},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Description},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Icon}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => EditCollectionItemRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $CollectionId) {
            throw "invalid value for 'CollectionId', 'CollectionId' cannot be null."
        }

        if ($null -eq $ItemId) {
            throw "invalid value for 'ItemId', 'ItemId' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "collectionId" = ${CollectionId}
            "itemId" = ${ItemId}
            "name" = ${Name}
            "description" = ${Description}
            "icon" = ${Icon}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to EditCollectionItemRequest<PSCustomObject>

.DESCRIPTION

Convert from JSON to EditCollectionItemRequest<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

EditCollectionItemRequest<PSCustomObject>
#>
function ConvertFrom-JsonToEditCollectionItemRequest {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => EditCollectionItemRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in EditCollectionItemRequest
        $AllProperties = ("collectionId", "itemId", "name", "description", "icon")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'collectionId' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "collectionId"))) {
            throw "Error! JSON cannot be serialized due to the required property 'collectionId' missing."
        } else {
            $CollectionId = $JsonParameters.PSobject.Properties["collectionId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "itemId"))) {
            throw "Error! JSON cannot be serialized due to the required property 'itemId' missing."
        } else {
            $ItemId = $JsonParameters.PSobject.Properties["itemId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "name"))) { #optional property not found
            $Name = $null
        } else {
            $Name = $JsonParameters.PSobject.Properties["name"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "description"))) { #optional property not found
            $Description = $null
        } else {
            $Description = $JsonParameters.PSobject.Properties["description"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "icon"))) { #optional property not found
            $Icon = $null
        } else {
            $Icon = $JsonParameters.PSobject.Properties["icon"].value
        }

        $PSO = [PSCustomObject]@{
            "collectionId" = ${CollectionId}
            "itemId" = ${ItemId}
            "name" = ${Name}
            "description" = ${Description}
            "icon" = ${Icon}
        }

        return $PSO
    }

}

