#
# Glean Client API
# # Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 
# Version: 0.9.0
# Contact: support@glean.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER AddedCollections
IDs of Collections to which a document is added.
.PARAMETER RemovedCollections
IDs of Collections from which a document is removed.
.PARAMETER DocumentId
The Glean Document ID of the item being added to or removed from Collections if it's an indexed document.
.PARAMETER Url
The URL of the item being added to or removed from Collections.
.PARAMETER Name
Custom title of the document if adding a non-indexed URL.
.PARAMETER Description
The description of this CollectionItem.
.OUTPUTS

EditDocumentCollectionsRequest<PSCustomObject>
#>

function Initialize-EditDocumentCollectionsRequest {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [Int32[]]
        ${AddedCollections},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [Int32[]]
        ${RemovedCollections},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${DocumentId},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Url},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Name},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Description}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => EditDocumentCollectionsRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "addedCollections" = ${AddedCollections}
            "removedCollections" = ${RemovedCollections}
            "documentId" = ${DocumentId}
            "url" = ${Url}
            "name" = ${Name}
            "description" = ${Description}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to EditDocumentCollectionsRequest<PSCustomObject>

.DESCRIPTION

Convert from JSON to EditDocumentCollectionsRequest<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

EditDocumentCollectionsRequest<PSCustomObject>
#>
function ConvertFrom-JsonToEditDocumentCollectionsRequest {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => EditDocumentCollectionsRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in EditDocumentCollectionsRequest
        $AllProperties = ("addedCollections", "removedCollections", "documentId", "url", "name", "description")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "addedCollections"))) { #optional property not found
            $AddedCollections = $null
        } else {
            $AddedCollections = $JsonParameters.PSobject.Properties["addedCollections"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "removedCollections"))) { #optional property not found
            $RemovedCollections = $null
        } else {
            $RemovedCollections = $JsonParameters.PSobject.Properties["removedCollections"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "documentId"))) { #optional property not found
            $DocumentId = $null
        } else {
            $DocumentId = $JsonParameters.PSobject.Properties["documentId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "url"))) { #optional property not found
            $Url = $null
        } else {
            $Url = $JsonParameters.PSobject.Properties["url"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "name"))) { #optional property not found
            $Name = $null
        } else {
            $Name = $JsonParameters.PSobject.Properties["name"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "description"))) { #optional property not found
            $Description = $null
        } else {
            $Description = $JsonParameters.PSobject.Properties["description"].value
        }

        $PSO = [PSCustomObject]@{
            "addedCollections" = ${AddedCollections}
            "removedCollections" = ${RemovedCollections}
            "documentId" = ${DocumentId}
            "url" = ${Url}
            "name" = ${Name}
            "description" = ${Description}
        }

        return $PSO
    }

}

