#
# Glean Client API
# # Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 
# Version: 0.9.0
# Contact: support@glean.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER DefaultChannels
The channels to which feedback will be sent for any feature that does not have specific configuration.
.PARAMETER FeatureChannels
The channels to which feedback will be sent for individual features. The keys of the map will match the values in FeedbackFeature. Features not present in the map should use defaultChannels.
.PARAMETER Disclaimer
A custom message shown to users during the in-product feedback flow, e.g. to warn users against sending sensitive or personally-identifying information.
.PARAMETER CompanyPrivacyPolicyLink
An optional link to a privacy policy provided by the users' company that will be shown to them during the in-product feedback flow if their company will receive their feedback. Glean's policy will also be shown if Glean is receiving the feedback.
.PARAMETER SupportMessage
User visible text shown when seeking support to guide them to their company's internal support page when appropriate
.PARAMETER SupportLinkText
User visible text that will link to the user's company's internal support page
.PARAMETER SupportLink
URL to the user's company's internal suport page
.OUTPUTS

FeedbackCustomizations<PSCustomObject>
#>

function Initialize-FeedbackCustomizations {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${DefaultChannels},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Collections.Hashtable]
        ${FeatureChannels},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Disclaimer},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${CompanyPrivacyPolicyLink},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${SupportMessage},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${SupportLinkText},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${SupportLink}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => FeedbackCustomizations' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "defaultChannels" = ${DefaultChannels}
            "featureChannels" = ${FeatureChannels}
            "disclaimer" = ${Disclaimer}
            "companyPrivacyPolicyLink" = ${CompanyPrivacyPolicyLink}
            "supportMessage" = ${SupportMessage}
            "supportLinkText" = ${SupportLinkText}
            "supportLink" = ${SupportLink}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to FeedbackCustomizations<PSCustomObject>

.DESCRIPTION

Convert from JSON to FeedbackCustomizations<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

FeedbackCustomizations<PSCustomObject>
#>
function ConvertFrom-JsonToFeedbackCustomizations {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => FeedbackCustomizations' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in FeedbackCustomizations
        $AllProperties = ("defaultChannels", "featureChannels", "disclaimer", "companyPrivacyPolicyLink", "supportMessage", "supportLinkText", "supportLink")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "defaultChannels"))) { #optional property not found
            $DefaultChannels = $null
        } else {
            $DefaultChannels = $JsonParameters.PSobject.Properties["defaultChannels"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "featureChannels"))) { #optional property not found
            $FeatureChannels = $null
        } else {
            $FeatureChannels = $JsonParameters.PSobject.Properties["featureChannels"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "disclaimer"))) { #optional property not found
            $Disclaimer = $null
        } else {
            $Disclaimer = $JsonParameters.PSobject.Properties["disclaimer"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "companyPrivacyPolicyLink"))) { #optional property not found
            $CompanyPrivacyPolicyLink = $null
        } else {
            $CompanyPrivacyPolicyLink = $JsonParameters.PSobject.Properties["companyPrivacyPolicyLink"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "supportMessage"))) { #optional property not found
            $SupportMessage = $null
        } else {
            $SupportMessage = $JsonParameters.PSobject.Properties["supportMessage"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "supportLinkText"))) { #optional property not found
            $SupportLinkText = $null
        } else {
            $SupportLinkText = $JsonParameters.PSobject.Properties["supportLinkText"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "supportLink"))) { #optional property not found
            $SupportLink = $null
        } else {
            $SupportLink = $JsonParameters.PSobject.Properties["supportLink"].value
        }

        $PSO = [PSCustomObject]@{
            "defaultChannels" = ${DefaultChannels}
            "featureChannels" = ${FeatureChannels}
            "disclaimer" = ${Disclaimer}
            "companyPrivacyPolicyLink" = ${CompanyPrivacyPolicyLink}
            "supportMessage" = ${SupportMessage}
            "supportLinkText" = ${SupportLinkText}
            "supportLink" = ${SupportLink}
        }

        return $PSO
    }

}

