#
# Glean Client API
# # Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 
# Version: 0.9.0
# Contact: support@glean.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Categories
Categories of content requested. An allowlist gives flexibility to request content separately or together.
.PARAMETER RequestOptions
No description available.
.PARAMETER TimeoutMillis
Timeout in milliseconds for the request. A `408` error will be returned if handling the request takes longer.
.PARAMETER SessionInfo
No description available.
.OUTPUTS

FeedRequest<PSCustomObject>
#>

function Initialize-FeedRequest {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("DOCUMENT_SUGGESTION", "DOCUMENT_SUGGESTION_SCENARIO", "TRENDING_DOCUMENT", "VERIFICATION_REMINDER", "EVENT", "ANNOUNCEMENT", "MENTION", "DATASOURCE_AFFINITY", "RECENT", "COMPANY_RESOURCE", "EXPERIMENTAL", "PEOPLE_CELEBRATIONS", "DISPLAYABLE_LIST", "SOCIAL_LINK", "EXTERNAL_TASKS", "ZERO_STATE_CHAT_SUGGESTION", "ZERO_STATE_CHAT_TOOL_SUGGESTION")]
        [String[]]
        ${Categories},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${RequestOptions},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${TimeoutMillis},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${SessionInfo}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => FeedRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "categories" = ${Categories}
            "requestOptions" = ${RequestOptions}
            "timeoutMillis" = ${TimeoutMillis}
            "sessionInfo" = ${SessionInfo}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to FeedRequest<PSCustomObject>

.DESCRIPTION

Convert from JSON to FeedRequest<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

FeedRequest<PSCustomObject>
#>
function ConvertFrom-JsonToFeedRequest {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => FeedRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in FeedRequest
        $AllProperties = ("categories", "requestOptions", "timeoutMillis", "sessionInfo")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "categories"))) { #optional property not found
            $Categories = $null
        } else {
            $Categories = $JsonParameters.PSobject.Properties["categories"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "requestOptions"))) { #optional property not found
            $RequestOptions = $null
        } else {
            $RequestOptions = $JsonParameters.PSobject.Properties["requestOptions"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "timeoutMillis"))) { #optional property not found
            $TimeoutMillis = $null
        } else {
            $TimeoutMillis = $JsonParameters.PSobject.Properties["timeoutMillis"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "sessionInfo"))) { #optional property not found
            $SessionInfo = $null
        } else {
            $SessionInfo = $JsonParameters.PSobject.Properties["sessionInfo"].value
        }

        $PSO = [PSCustomObject]@{
            "categories" = ${Categories}
            "requestOptions" = ${RequestOptions}
            "timeoutMillis" = ${TimeoutMillis}
            "sessionInfo" = ${SessionInfo}
        }

        return $PSO
    }

}

