#
# Glean Client API
# # Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 
# Version: 0.9.0
# Contact: support@glean.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER DocumentSpecs
The specification for the documents to be retrieved.
.PARAMETER IncludeFields
List of Document fields to return (that aren't returned by default)
.OUTPUTS

GetDocumentsRequest<PSCustomObject>
#>

function Initialize-GetDocumentsRequest {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${DocumentSpecs},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("LAST_VIEWED_AT", "VISITORS_COUNT", "RECENT_SHARES", "DOCUMENT_CONTENT")]
        [String[]]
        ${IncludeFields}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => GetDocumentsRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $DocumentSpecs) {
            throw "invalid value for 'DocumentSpecs', 'DocumentSpecs' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "documentSpecs" = ${DocumentSpecs}
            "includeFields" = ${IncludeFields}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to GetDocumentsRequest<PSCustomObject>

.DESCRIPTION

Convert from JSON to GetDocumentsRequest<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

GetDocumentsRequest<PSCustomObject>
#>
function ConvertFrom-JsonToGetDocumentsRequest {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => GetDocumentsRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in GetDocumentsRequest
        $AllProperties = ("documentSpecs", "includeFields")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'documentSpecs' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "documentSpecs"))) {
            throw "Error! JSON cannot be serialized due to the required property 'documentSpecs' missing."
        } else {
            $DocumentSpecs = $JsonParameters.PSobject.Properties["documentSpecs"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "includeFields"))) { #optional property not found
            $IncludeFields = $null
        } else {
            $IncludeFields = $JsonParameters.PSobject.Properties["includeFields"].value
        }

        $PSO = [PSCustomObject]@{
            "documentSpecs" = ${DocumentSpecs}
            "includeFields" = ${IncludeFields}
        }

        return $PSO
    }

}

