#
# Glean Client API
# # Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 
# Version: 0.9.0
# Contact: support@glean.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Ids
The ids of the calendar events to be retrieved.
.PARAMETER AuthTokens
Auth tokens if client-side authentication.
.PARAMETER Datasource
The app or other repository type from which the event was extracted
.PARAMETER Annotate
Whether relevant content and documents, via GeneratedAttachments, should be attached to the events.
.OUTPUTS

GetEventsRequest<PSCustomObject>
#>

function Initialize-GetEventsRequest {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${Ids},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${AuthTokens},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Datasource},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${Annotate}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => GetEventsRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $Ids) {
            throw "invalid value for 'Ids', 'Ids' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "ids" = ${Ids}
            "authTokens" = ${AuthTokens}
            "datasource" = ${Datasource}
            "annotate" = ${Annotate}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to GetEventsRequest<PSCustomObject>

.DESCRIPTION

Convert from JSON to GetEventsRequest<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

GetEventsRequest<PSCustomObject>
#>
function ConvertFrom-JsonToGetEventsRequest {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => GetEventsRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in GetEventsRequest
        $AllProperties = ("ids", "authTokens", "datasource", "annotate")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'ids' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "ids"))) {
            throw "Error! JSON cannot be serialized due to the required property 'ids' missing."
        } else {
            $Ids = $JsonParameters.PSobject.Properties["ids"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "authTokens"))) { #optional property not found
            $AuthTokens = $null
        } else {
            $AuthTokens = $JsonParameters.PSobject.Properties["authTokens"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "datasource"))) { #optional property not found
            $Datasource = $null
        } else {
            $Datasource = $JsonParameters.PSobject.Properties["datasource"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "annotate"))) { #optional property not found
            $Annotate = $null
        } else {
            $Annotate = $JsonParameters.PSobject.Properties["annotate"].value
        }

        $PSO = [PSCustomObject]@{
            "ids" = ${Ids}
            "authTokens" = ${AuthTokens}
            "datasource" = ${Datasource}
            "annotate" = ${Annotate}
        }

        return $PSO
    }

}

