#
# Glean Client API
# # Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 
# Version: 0.9.0
# Contact: support@glean.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

A request to send an invite to the specified user[s]

.PARAMETER Channel
No description available.
.PARAMETER Template
No description available.
.PARAMETER Recipients
The people who should receive this invite
.PARAMETER RecipientFilters
No description available.
.OUTPUTS

InviteRequest<PSCustomObject>
#>

function Initialize-InviteRequest {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("COMMUNICATION_CHANNEL_EMAIL", "COMMUNICATION_CHANNEL_SLACK")]
        [PSCustomObject]
        ${Channel},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("ADMIN_ALERT", "ADMIN_ALERT_V2", "ADMIN_INVITE", "ASSISTANT_ACCESS", "AUTO_INVITE", "CHAT_FEEDBACK", "CUSTOM_JSON_REPORT", "DOMAIN_VERIFICATION", "GENERAL_FEEDBACK", "INVITE_REMINDER", "MANAGER_INVITE", "ONBOARDING_CHAT", "ONBOARDING_INTRO", "ONBOARDING_EXPLORE", "ONBOARDING_EXPLORE_EXTENSION_PROMO", "ONBOARDING_TIPS", "ONBOARDING_TIPS_EXTENSION_PROMO", "ONBOARDING_SURVEY", "RECRAWL_DATASOURCE", "REPORT_ISSUE_FEEDBACK", "SEARCH_FEEDBACK", "TEAMMATE_INVITE", "VERIFICATION_REQUEST", "VERIFICATION_REQUEST_NONUSER", "WEEKLY_FEED", "WORKSPACE_INITIALIZED")]
        [PSCustomObject]
        ${Template},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Recipients},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${RecipientFilters}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => InviteRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "channel" = ${Channel}
            "template" = ${Template}
            "recipients" = ${Recipients}
            "recipientFilters" = ${RecipientFilters}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to InviteRequest<PSCustomObject>

.DESCRIPTION

Convert from JSON to InviteRequest<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

InviteRequest<PSCustomObject>
#>
function ConvertFrom-JsonToInviteRequest {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => InviteRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in InviteRequest
        $AllProperties = ("channel", "template", "recipients", "recipientFilters")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "channel"))) { #optional property not found
            $Channel = $null
        } else {
            $Channel = $JsonParameters.PSobject.Properties["channel"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "template"))) { #optional property not found
            $Template = $null
        } else {
            $Template = $JsonParameters.PSobject.Properties["template"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "recipients"))) { #optional property not found
            $Recipients = $null
        } else {
            $Recipients = $JsonParameters.PSobject.Properties["recipients"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "recipientFilters"))) { #optional property not found
            $RecipientFilters = $null
        } else {
            $RecipientFilters = $JsonParameters.PSobject.Properties["recipientFilters"].value
        }

        $PSO = [PSCustomObject]@{
            "channel" = ${Channel}
            "template" = ${Template}
            "recipients" = ${Recipients}
            "recipientFilters" = ${RecipientFilters}
        }

        return $PSO
    }

}

