#
# Glean Client API
# # Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 
# Version: 0.9.0
# Contact: support@glean.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER IncludeFields
Array of fields/data to be included in response that are not included by default
.PARAMETER PageSize
No description available.
.PARAMETER Cursor
A token specifying the position in the overall results to start at. Received from the endpoint and iterated back. Currently being used as page no (as we implement offset pagination)
.PARAMETER Filters
A list of filters for the query. An AND is assumed between different filters. We support filters on Go Link name, author, department and type.
.PARAMETER Sort
No description available.
.PARAMETER Query
Search query that should be a substring in atleast one of the fields (alias , inputAlias, destinationUrl, description). Empty query does not filter shortcuts.
.OUTPUTS

ListShortcutsPaginatedRequest<PSCustomObject>
#>

function Initialize-ListShortcutsPaginatedRequest {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("FACETS", "PEOPLE_DETAILS")]
        [String[]]
        ${IncludeFields},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [Int32]
        ${PageSize},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Cursor},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Filters},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Sort},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Query}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => ListShortcutsPaginatedRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $PageSize) {
            throw "invalid value for 'PageSize', 'PageSize' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "includeFields" = ${IncludeFields}
            "pageSize" = ${PageSize}
            "cursor" = ${Cursor}
            "filters" = ${Filters}
            "sort" = ${Sort}
            "query" = ${Query}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ListShortcutsPaginatedRequest<PSCustomObject>

.DESCRIPTION

Convert from JSON to ListShortcutsPaginatedRequest<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ListShortcutsPaginatedRequest<PSCustomObject>
#>
function ConvertFrom-JsonToListShortcutsPaginatedRequest {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => ListShortcutsPaginatedRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in ListShortcutsPaginatedRequest
        $AllProperties = ("includeFields", "pageSize", "cursor", "filters", "sort", "query")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'pageSize' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "pageSize"))) {
            throw "Error! JSON cannot be serialized due to the required property 'pageSize' missing."
        } else {
            $PageSize = $JsonParameters.PSobject.Properties["pageSize"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "includeFields"))) { #optional property not found
            $IncludeFields = $null
        } else {
            $IncludeFields = $JsonParameters.PSobject.Properties["includeFields"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "cursor"))) { #optional property not found
            $Cursor = $null
        } else {
            $Cursor = $JsonParameters.PSobject.Properties["cursor"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "filters"))) { #optional property not found
            $Filters = $null
        } else {
            $Filters = $JsonParameters.PSobject.Properties["filters"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "sort"))) { #optional property not found
            $Sort = $null
        } else {
            $Sort = $JsonParameters.PSobject.Properties["sort"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "query"))) { #optional property not found
            $Query = $null
        } else {
            $Query = $JsonParameters.PSobject.Properties["query"].value
        }

        $PSO = [PSCustomObject]@{
            "includeFields" = ${IncludeFields}
            "pageSize" = ${PageSize}
            "cursor" = ${Cursor}
            "filters" = ${Filters}
            "sort" = ${Sort}
            "query" = ${Query}
        }

        return $PSO
    }

}

