#
# Glean Client API
# # Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 
# Version: 0.9.0
# Contact: support@glean.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Shortcuts
List of all shortcuts accessible to the user
.PARAMETER FacetResults
No description available.
.PARAMETER Meta
No description available.
.OUTPUTS

ListShortcutsPaginatedResponse<PSCustomObject>
#>

function Initialize-ListShortcutsPaginatedResponse {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Shortcuts},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${FacetResults},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Meta}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => ListShortcutsPaginatedResponse' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $Shortcuts) {
            throw "invalid value for 'Shortcuts', 'Shortcuts' cannot be null."
        }

        if ($null -eq $Meta) {
            throw "invalid value for 'Meta', 'Meta' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "shortcuts" = ${Shortcuts}
            "facetResults" = ${FacetResults}
            "meta" = ${Meta}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ListShortcutsPaginatedResponse<PSCustomObject>

.DESCRIPTION

Convert from JSON to ListShortcutsPaginatedResponse<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ListShortcutsPaginatedResponse<PSCustomObject>
#>
function ConvertFrom-JsonToListShortcutsPaginatedResponse {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => ListShortcutsPaginatedResponse' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in ListShortcutsPaginatedResponse
        $AllProperties = ("shortcuts", "facetResults", "meta")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'shortcuts' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "shortcuts"))) {
            throw "Error! JSON cannot be serialized due to the required property 'shortcuts' missing."
        } else {
            $Shortcuts = $JsonParameters.PSobject.Properties["shortcuts"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "meta"))) {
            throw "Error! JSON cannot be serialized due to the required property 'meta' missing."
        } else {
            $Meta = $JsonParameters.PSobject.Properties["meta"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "facetResults"))) { #optional property not found
            $FacetResults = $null
        } else {
            $FacetResults = $JsonParameters.PSobject.Properties["facetResults"].value
        }

        $PSO = [PSCustomObject]@{
            "shortcuts" = ${Shortcuts}
            "facetResults" = ${FacetResults}
            "meta" = ${Meta}
        }

        return $PSO
    }

}

