#
# Glean Client API
# # Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 
# Version: 0.9.0
# Contact: support@glean.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER IdType
Type of the id in the incoming request.
.PARAMETER Id
ID corresponding to the requested idType. Note that channel and threads are represented by the underlying datasource's ID and conversations are represented by their document's ID.
.PARAMETER WorkspaceId
Id for the for the workspace in case of multiple workspaces.
.PARAMETER Direction
The direction of the results asked with respect to the reference timestamp. Missing field defaults to OLDER.
.PARAMETER TimestampMillis
Timestamp in millis of the reference message.
.PARAMETER IncludeRootMessage
Whether to include root message in response.
.PARAMETER Datasource
The type of the data source. Missing field defaults to SLACK.
.PARAMETER DatasourceInstanceDisplayName
The datasource instance display name from which the document was extracted. This is used for appinstance facet filter for datasources that support multiple instances.
.OUTPUTS

MessagesRequest<PSCustomObject>
#>

function Initialize-MessagesRequest {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("CHANNEL_NAME", "THREAD_ID", "CONVERSATION_ID")]
        [String]
        ${IdType},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Id},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${WorkspaceId},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("OLDER", "NEWER")]
        [String]
        ${Direction},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [Int64]
        ${TimestampMillis},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${IncludeRootMessage},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("SLACK", "MICROSOFTTEAMS", "FACEBOOKWORKPLACE")]
        [String]
        ${Datasource},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${DatasourceInstanceDisplayName}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => MessagesRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $IdType) {
            throw "invalid value for 'IdType', 'IdType' cannot be null."
        }

        if ($null -eq $Id) {
            throw "invalid value for 'Id', 'Id' cannot be null."
        }

        if ($null -eq $TimestampMillis) {
            throw "invalid value for 'TimestampMillis', 'TimestampMillis' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "idType" = ${IdType}
            "id" = ${Id}
            "workspaceId" = ${WorkspaceId}
            "direction" = ${Direction}
            "timestampMillis" = ${TimestampMillis}
            "includeRootMessage" = ${IncludeRootMessage}
            "datasource" = ${Datasource}
            "datasourceInstanceDisplayName" = ${DatasourceInstanceDisplayName}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to MessagesRequest<PSCustomObject>

.DESCRIPTION

Convert from JSON to MessagesRequest<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

MessagesRequest<PSCustomObject>
#>
function ConvertFrom-JsonToMessagesRequest {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => MessagesRequest' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in MessagesRequest
        $AllProperties = ("idType", "id", "workspaceId", "direction", "timestampMillis", "includeRootMessage", "datasource", "datasourceInstanceDisplayName")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'idType' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "idType"))) {
            throw "Error! JSON cannot be serialized due to the required property 'idType' missing."
        } else {
            $IdType = $JsonParameters.PSobject.Properties["idType"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "id"))) {
            throw "Error! JSON cannot be serialized due to the required property 'id' missing."
        } else {
            $Id = $JsonParameters.PSobject.Properties["id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "timestampMillis"))) {
            throw "Error! JSON cannot be serialized due to the required property 'timestampMillis' missing."
        } else {
            $TimestampMillis = $JsonParameters.PSobject.Properties["timestampMillis"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "workspaceId"))) { #optional property not found
            $WorkspaceId = $null
        } else {
            $WorkspaceId = $JsonParameters.PSobject.Properties["workspaceId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "direction"))) { #optional property not found
            $Direction = $null
        } else {
            $Direction = $JsonParameters.PSobject.Properties["direction"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "includeRootMessage"))) { #optional property not found
            $IncludeRootMessage = $null
        } else {
            $IncludeRootMessage = $JsonParameters.PSobject.Properties["includeRootMessage"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "datasource"))) { #optional property not found
            $Datasource = $null
        } else {
            $Datasource = $JsonParameters.PSobject.Properties["datasource"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "datasourceInstanceDisplayName"))) { #optional property not found
            $DatasourceInstanceDisplayName = $null
        } else {
            $DatasourceInstanceDisplayName = $JsonParameters.PSobject.Properties["datasourceInstanceDisplayName"].value
        }

        $PSO = [PSCustomObject]@{
            "idType" = ${IdType}
            "id" = ${Id}
            "workspaceId" = ${WorkspaceId}
            "direction" = ${Direction}
            "timestampMillis" = ${TimestampMillis}
            "includeRootMessage" = ${IncludeRootMessage}
            "datasource" = ${Datasource}
            "datasourceInstanceDisplayName" = ${DatasourceInstanceDisplayName}
        }

        return $PSO
    }

}

