#
# Glean Client API
# # Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 
# Version: 0.9.0
# Contact: support@glean.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER MinDaysFromNow
DEPRECATED - The number of days from now in the past to define upper boundary of time period.
.PARAMETER MaxDaysFromNow
DEPRECATED - The number of days from now in the past to define lower boundary of time period.
.PARAMETER Start
No description available.
.PARAMETER VarEnd
No description available.
.OUTPUTS

Period<PSCustomObject>
#>

function Initialize-Period {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${MinDaysFromNow},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${MaxDaysFromNow},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Start},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${VarEnd}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => Period' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "minDaysFromNow" = ${MinDaysFromNow}
            "maxDaysFromNow" = ${MaxDaysFromNow}
            "start" = ${Start}
            "end" = ${VarEnd}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to Period<PSCustomObject>

.DESCRIPTION

Convert from JSON to Period<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

Period<PSCustomObject>
#>
function ConvertFrom-JsonToPeriod {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => Period' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in Period
        $AllProperties = ("minDaysFromNow", "maxDaysFromNow", "start", "end")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "minDaysFromNow"))) { #optional property not found
            $MinDaysFromNow = $null
        } else {
            $MinDaysFromNow = $JsonParameters.PSobject.Properties["minDaysFromNow"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "maxDaysFromNow"))) { #optional property not found
            $MaxDaysFromNow = $null
        } else {
            $MaxDaysFromNow = $JsonParameters.PSobject.Properties["maxDaysFromNow"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "start"))) { #optional property not found
            $Start = $null
        } else {
            $Start = $JsonParameters.PSobject.Properties["start"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "end"))) { #optional property not found
            $VarEnd = $null
        } else {
            $VarEnd = $JsonParameters.PSobject.Properties["end"].value
        }

        $PSO = [PSCustomObject]@{
            "minDaysFromNow" = ${MinDaysFromNow}
            "maxDaysFromNow" = ${MaxDaysFromNow}
            "start" = ${Start}
            "end" = ${VarEnd}
        }

        return $PSO
    }

}

