#
# Glean Client API
# # Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 
# Version: 0.9.0
# Contact: support@glean.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Use `id` if you index teams via Glean, and use `name` and `externalLink` if you want to use your own team pages

.PARAMETER Id
Unique identifier
.PARAMETER Name
Team name
.PARAMETER ExternalLink
Link to a team page on the internet or your company's intranet
.PARAMETER Relationship
The team member's relationship to the team. This defaults to MEMBER if not set.
.PARAMETER JoinDate
The team member's start date
.OUTPUTS

PersonTeam<PSCustomObject>
#>

function Initialize-PersonTeam {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Id},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Name},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ExternalLink},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("MEMBER", "MANAGER", "LEAD", "POINT_OF_CONTACT", "OTHER")]
        [String]
        ${Relationship} = "MEMBER",
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[System.DateTime]]
        ${JoinDate}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => PersonTeam' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "id" = ${Id}
            "name" = ${Name}
            "externalLink" = ${ExternalLink}
            "relationship" = ${Relationship}
            "joinDate" = ${JoinDate}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to PersonTeam<PSCustomObject>

.DESCRIPTION

Convert from JSON to PersonTeam<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

PersonTeam<PSCustomObject>
#>
function ConvertFrom-JsonToPersonTeam {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => PersonTeam' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in PersonTeam
        $AllProperties = ("id", "name", "externalLink", "relationship", "joinDate")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "id"))) { #optional property not found
            $Id = $null
        } else {
            $Id = $JsonParameters.PSobject.Properties["id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "name"))) { #optional property not found
            $Name = $null
        } else {
            $Name = $JsonParameters.PSobject.Properties["name"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "externalLink"))) { #optional property not found
            $ExternalLink = $null
        } else {
            $ExternalLink = $JsonParameters.PSobject.Properties["externalLink"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "relationship"))) { #optional property not found
            $Relationship = $null
        } else {
            $Relationship = $JsonParameters.PSobject.Properties["relationship"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "joinDate"))) { #optional property not found
            $JoinDate = $null
        } else {
            $JoinDate = $JsonParameters.PSobject.Properties["joinDate"].value
        }

        $PSO = [PSCustomObject]@{
            "id" = ${Id}
            "name" = ${Name}
            "externalLink" = ${ExternalLink}
            "relationship" = ${Relationship}
            "joinDate" = ${JoinDate}
        }

        return $PSO
    }

}

