#
# Glean Client API
# # Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 
# Version: 0.9.0
# Contact: support@glean.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Name
The display name.
.PARAMETER ObfuscatedId
An opaque identifier that can be used to request metadata for a Person.
.PARAMETER Distance
Distance to person, refer to PeopleDistance pipeline on interpretation of the value.
.OUTPUTS

PersonDistance<PSCustomObject>
#>

function Initialize-PersonDistance {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Name},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ObfuscatedId},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [Double]
        ${Distance}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => PersonDistance' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $Name) {
            throw "invalid value for 'Name', 'Name' cannot be null."
        }

        if ($null -eq $ObfuscatedId) {
            throw "invalid value for 'ObfuscatedId', 'ObfuscatedId' cannot be null."
        }

        if ($null -eq $Distance) {
            throw "invalid value for 'Distance', 'Distance' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "name" = ${Name}
            "obfuscatedId" = ${ObfuscatedId}
            "distance" = ${Distance}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to PersonDistance<PSCustomObject>

.DESCRIPTION

Convert from JSON to PersonDistance<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

PersonDistance<PSCustomObject>
#>
function ConvertFrom-JsonToPersonDistance {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => PersonDistance' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in PersonDistance
        $AllProperties = ("name", "obfuscatedId", "distance")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'name' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "name"))) {
            throw "Error! JSON cannot be serialized due to the required property 'name' missing."
        } else {
            $Name = $JsonParameters.PSobject.Properties["name"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "obfuscatedId"))) {
            throw "Error! JSON cannot be serialized due to the required property 'obfuscatedId' missing."
        } else {
            $ObfuscatedId = $JsonParameters.PSobject.Properties["obfuscatedId"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "distance"))) {
            throw "Error! JSON cannot be serialized due to the required property 'distance' missing."
        } else {
            $Distance = $JsonParameters.PSobject.Properties["distance"].value
        }

        $PSO = [PSCustomObject]@{
            "name" = ${Name}
            "obfuscatedId" = ${ObfuscatedId}
            "distance" = ${Distance}
        }

        return $PSO
    }

}

