#
# Glean Client API
# # Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 
# Version: 0.9.0
# Contact: support@glean.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER StructuredText
No description available.
.PARAMETER DocsInaccessibleToUser
A list of links the user doesn't have access to.
.PARAMETER CombinedAnswerText
No description available.
.OUTPUTS

PreviewStructuredTextResponse<PSCustomObject>
#>

function Initialize-PreviewStructuredTextResponse {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${StructuredText},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${DocsInaccessibleToUser},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${CombinedAnswerText}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => PreviewStructuredTextResponse' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $StructuredText) {
            throw "invalid value for 'StructuredText', 'StructuredText' cannot be null."
        }

        if ($null -eq $CombinedAnswerText) {
            throw "invalid value for 'CombinedAnswerText', 'CombinedAnswerText' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "structuredText" = ${StructuredText}
            "docsInaccessibleToUser" = ${DocsInaccessibleToUser}
            "combinedAnswerText" = ${CombinedAnswerText}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to PreviewStructuredTextResponse<PSCustomObject>

.DESCRIPTION

Convert from JSON to PreviewStructuredTextResponse<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

PreviewStructuredTextResponse<PSCustomObject>
#>
function ConvertFrom-JsonToPreviewStructuredTextResponse {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => PreviewStructuredTextResponse' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in PreviewStructuredTextResponse
        $AllProperties = ("structuredText", "docsInaccessibleToUser", "combinedAnswerText")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'structuredText' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "structuredText"))) {
            throw "Error! JSON cannot be serialized due to the required property 'structuredText' missing."
        } else {
            $StructuredText = $JsonParameters.PSobject.Properties["structuredText"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "combinedAnswerText"))) {
            throw "Error! JSON cannot be serialized due to the required property 'combinedAnswerText' missing."
        } else {
            $CombinedAnswerText = $JsonParameters.PSobject.Properties["combinedAnswerText"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "docsInaccessibleToUser"))) { #optional property not found
            $DocsInaccessibleToUser = $null
        } else {
            $DocsInaccessibleToUser = $JsonParameters.PSobject.Properties["docsInaccessibleToUser"].value
        }

        $PSO = [PSCustomObject]@{
            "structuredText" = ${StructuredText}
            "docsInaccessibleToUser" = ${DocsInaccessibleToUser}
            "combinedAnswerText" = ${CombinedAnswerText}
        }

        return $PSO
    }

}

