#
# Glean Client API
# # Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 
# Version: 0.9.0
# Contact: support@glean.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Type
No description available.
.PARAMETER Count
The count of the reaction type on the document.
.PARAMETER Reactors
No description available.
.PARAMETER ReactedByViewer
Whether the user in context reacted with this type to the document.
.OUTPUTS

Reaction<PSCustomObject>
#>

function Initialize-Reaction {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Type},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Count},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Reactors},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${ReactedByViewer}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => Reaction' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "type" = ${Type}
            "count" = ${Count}
            "reactors" = ${Reactors}
            "reactedByViewer" = ${ReactedByViewer}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to Reaction<PSCustomObject>

.DESCRIPTION

Convert from JSON to Reaction<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

Reaction<PSCustomObject>
#>
function ConvertFrom-JsonToReaction {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => Reaction' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in Reaction
        $AllProperties = ("type", "count", "reactors", "reactedByViewer")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "type"))) { #optional property not found
            $Type = $null
        } else {
            $Type = $JsonParameters.PSobject.Properties["type"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "count"))) { #optional property not found
            $Count = $null
        } else {
            $Count = $JsonParameters.PSobject.Properties["count"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "reactors"))) { #optional property not found
            $Reactors = $null
        } else {
            $Reactors = $JsonParameters.PSobject.Properties["reactors"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "reactedByViewer"))) { #optional property not found
            $ReactedByViewer = $null
        } else {
            $ReactedByViewer = $JsonParameters.PSobject.Properties["reactedByViewer"].value
        }

        $PSO = [PSCustomObject]@{
            "type" = ${Type}
            "count" = ${Count}
            "reactors" = ${Reactors}
            "reactedByViewer" = ${ReactedByViewer}
        }

        return $PSO
    }

}

