#
# Glean Client API
# # Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 
# Version: 0.9.0
# Contact: support@glean.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Each text range from the response can correspond to an array of snippets from the citation source.

.PARAMETER TextRange
No description available.
.PARAMETER Snippets
No description available.
.OUTPUTS

ReferenceRange<PSCustomObject>
#>

function Initialize-ReferenceRange {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${TextRange},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Snippets}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => ReferenceRange' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $TextRange) {
            throw "invalid value for 'TextRange', 'TextRange' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "textRange" = ${TextRange}
            "snippets" = ${Snippets}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ReferenceRange<PSCustomObject>

.DESCRIPTION

Convert from JSON to ReferenceRange<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ReferenceRange<PSCustomObject>
#>
function ConvertFrom-JsonToReferenceRange {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => ReferenceRange' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in ReferenceRange
        $AllProperties = ("textRange", "snippets")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'textRange' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "textRange"))) {
            throw "Error! JSON cannot be serialized due to the required property 'textRange' missing."
        } else {
            $TextRange = $JsonParameters.PSobject.Properties["textRange"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "snippets"))) { #optional property not found
            $Snippets = $null
        } else {
            $Snippets = $JsonParameters.PSobject.Properties["snippets"].value
        }

        $PSO = [PSCustomObject]@{
            "textRange" = ${TextRange}
            "snippets" = ${Snippets}
        }

        return $PSO
    }

}

