#
# Glean Client API
# # Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 
# Version: 0.9.0
# Contact: support@glean.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Question
The text of the related question
.PARAMETER Answer
The answer for the related question
.PARAMETER Ranges
Subsections of the answer string to which some special formatting should be applied (eg. bold)
.OUTPUTS

RelatedQuestion<PSCustomObject>
#>

function Initialize-RelatedQuestion {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Question},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Answer},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Ranges}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => RelatedQuestion' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "question" = ${Question}
            "answer" = ${Answer}
            "ranges" = ${Ranges}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to RelatedQuestion<PSCustomObject>

.DESCRIPTION

Convert from JSON to RelatedQuestion<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

RelatedQuestion<PSCustomObject>
#>
function ConvertFrom-JsonToRelatedQuestion {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => RelatedQuestion' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in RelatedQuestion
        $AllProperties = ("question", "answer", "ranges")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "question"))) { #optional property not found
            $Question = $null
        } else {
            $Question = $JsonParameters.PSobject.Properties["question"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "answer"))) { #optional property not found
            $Answer = $null
        } else {
            $Answer = $JsonParameters.PSobject.Properties["answer"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "ranges"))) { #optional property not found
            $Ranges = $null
        } else {
            $Ranges = $JsonParameters.PSobject.Properties["ranges"].value
        }

        $PSO = [PSCustomObject]@{
            "question" = ${Question}
            "answer" = ${Answer}
            "ranges" = ${Ranges}
        }

        return $PSO
    }

}

