#
# Glean Client API
# # Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 
# Version: 0.9.0
# Contact: support@glean.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Assignee
No description available.
.PARAMETER Requestor
No description available.
.PARAMETER RemindAt
Unix timestamp for when the reminder should trigger (in seconds since epoch UTC).
.PARAMETER CreatedAt
Unix timestamp for when the reminder was first created (in seconds since epoch UTC).
.PARAMETER Reason
An optional free-text reason for the reminder. This is particularly useful when a reminder is used to ask for verification from another user (for example, ""Duplicate"", ""Incomplete"", ""Incorrect"").
.OUTPUTS

Reminder<PSCustomObject>
#>

function Initialize-Reminder {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Assignee},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Requestor},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [Int32]
        ${RemindAt},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${CreatedAt},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Reason}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => Reminder' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $Assignee) {
            throw "invalid value for 'Assignee', 'Assignee' cannot be null."
        }

        if ($null -eq $RemindAt) {
            throw "invalid value for 'RemindAt', 'RemindAt' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "assignee" = ${Assignee}
            "requestor" = ${Requestor}
            "remindAt" = ${RemindAt}
            "createdAt" = ${CreatedAt}
            "reason" = ${Reason}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to Reminder<PSCustomObject>

.DESCRIPTION

Convert from JSON to Reminder<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

Reminder<PSCustomObject>
#>
function ConvertFrom-JsonToReminder {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => Reminder' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in Reminder
        $AllProperties = ("assignee", "requestor", "remindAt", "createdAt", "reason")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'assignee' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "assignee"))) {
            throw "Error! JSON cannot be serialized due to the required property 'assignee' missing."
        } else {
            $Assignee = $JsonParameters.PSobject.Properties["assignee"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "remindAt"))) {
            throw "Error! JSON cannot be serialized due to the required property 'remindAt' missing."
        } else {
            $RemindAt = $JsonParameters.PSobject.Properties["remindAt"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "requestor"))) { #optional property not found
            $Requestor = $null
        } else {
            $Requestor = $JsonParameters.PSobject.Properties["requestor"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "createdAt"))) { #optional property not found
            $CreatedAt = $null
        } else {
            $CreatedAt = $JsonParameters.PSobject.Properties["createdAt"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "reason"))) { #optional property not found
            $Reason = $null
        } else {
            $Reason = $JsonParameters.PSobject.Properties["reason"].value
        }

        $PSO = [PSCustomObject]@{
            "assignee" = ${Assignee}
            "requestor" = ${Requestor}
            "remindAt" = ${RemindAt}
            "createdAt" = ${CreatedAt}
            "reason" = ${Reason}
        }

        return $PSO
    }

}

