#
# Glean Client API
# # Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 
# Version: 0.9.0
# Contact: support@glean.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER TrackingToken
A token that should be passed for additional requests related to this request (such as more results requests).
.PARAMETER SessionInfo
No description available.
.PARAMETER Results
No description available.
.PARAMETER StructuredResults
No description available.
.PARAMETER GeneratedQnaResult
No description available.
.PARAMETER ErrorInfo
No description available.
.PARAMETER RequestID
A platform-generated request ID to correlate backend logs.
.PARAMETER BackendTimeMillis
Time in milliseconds the backend took to respond to the request.
.PARAMETER ExperimentIds
List of experiment ids for the corresponding request.
.PARAMETER Metadata
No description available.
.PARAMETER FacetResults
No description available.
.PARAMETER ResultTabs
All result tabs available for the current query. Populated if QUERY_METADATA is specified in the request.
.PARAMETER ResultTabIds
The unique IDs of the result tabs to which this response belongs.
.PARAMETER ResultsDescription
No description available.
.PARAMETER RewrittenFacetFilters
The actual applied facet filters based on the operators and facetFilters in the query. Useful for mapping typed operators to visual facets.
.PARAMETER Cursor
Cursor that indicates the start of the next page of results. To be passed in ""more"" requests for this query.
.PARAMETER HasMoreResults
Whether more results are available. Use cursor to retrieve them.
.OUTPUTS

SearchResponse<PSCustomObject>
#>

function Initialize-SearchResponse {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${TrackingToken},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${SessionInfo},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Results},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${StructuredResults},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${GeneratedQnaResult},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${ErrorInfo},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${RequestID},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int64]]
        ${BackendTimeMillis},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [Int64[]]
        ${ExperimentIds},
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Metadata},
        [Parameter(Position = 10, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${FacetResults},
        [Parameter(Position = 11, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${ResultTabs},
        [Parameter(Position = 12, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${ResultTabIds},
        [Parameter(Position = 13, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${ResultsDescription},
        [Parameter(Position = 14, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${RewrittenFacetFilters},
        [Parameter(Position = 15, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Cursor},
        [Parameter(Position = 16, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${HasMoreResults}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => SearchResponse' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "trackingToken" = ${TrackingToken}
            "sessionInfo" = ${SessionInfo}
            "results" = ${Results}
            "structuredResults" = ${StructuredResults}
            "generatedQnaResult" = ${GeneratedQnaResult}
            "errorInfo" = ${ErrorInfo}
            "requestID" = ${RequestID}
            "backendTimeMillis" = ${BackendTimeMillis}
            "experimentIds" = ${ExperimentIds}
            "metadata" = ${Metadata}
            "facetResults" = ${FacetResults}
            "resultTabs" = ${ResultTabs}
            "resultTabIds" = ${ResultTabIds}
            "resultsDescription" = ${ResultsDescription}
            "rewrittenFacetFilters" = ${RewrittenFacetFilters}
            "cursor" = ${Cursor}
            "hasMoreResults" = ${HasMoreResults}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to SearchResponse<PSCustomObject>

.DESCRIPTION

Convert from JSON to SearchResponse<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

SearchResponse<PSCustomObject>
#>
function ConvertFrom-JsonToSearchResponse {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => SearchResponse' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in SearchResponse
        $AllProperties = ("trackingToken", "sessionInfo", "results", "structuredResults", "generatedQnaResult", "errorInfo", "requestID", "backendTimeMillis", "experimentIds", "metadata", "facetResults", "resultTabs", "resultTabIds", "resultsDescription", "rewrittenFacetFilters", "cursor", "hasMoreResults")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "trackingToken"))) { #optional property not found
            $TrackingToken = $null
        } else {
            $TrackingToken = $JsonParameters.PSobject.Properties["trackingToken"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "sessionInfo"))) { #optional property not found
            $SessionInfo = $null
        } else {
            $SessionInfo = $JsonParameters.PSobject.Properties["sessionInfo"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "results"))) { #optional property not found
            $Results = $null
        } else {
            $Results = $JsonParameters.PSobject.Properties["results"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "structuredResults"))) { #optional property not found
            $StructuredResults = $null
        } else {
            $StructuredResults = $JsonParameters.PSobject.Properties["structuredResults"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "generatedQnaResult"))) { #optional property not found
            $GeneratedQnaResult = $null
        } else {
            $GeneratedQnaResult = $JsonParameters.PSobject.Properties["generatedQnaResult"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "errorInfo"))) { #optional property not found
            $ErrorInfo = $null
        } else {
            $ErrorInfo = $JsonParameters.PSobject.Properties["errorInfo"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "requestID"))) { #optional property not found
            $RequestID = $null
        } else {
            $RequestID = $JsonParameters.PSobject.Properties["requestID"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "backendTimeMillis"))) { #optional property not found
            $BackendTimeMillis = $null
        } else {
            $BackendTimeMillis = $JsonParameters.PSobject.Properties["backendTimeMillis"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "experimentIds"))) { #optional property not found
            $ExperimentIds = $null
        } else {
            $ExperimentIds = $JsonParameters.PSobject.Properties["experimentIds"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "metadata"))) { #optional property not found
            $Metadata = $null
        } else {
            $Metadata = $JsonParameters.PSobject.Properties["metadata"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "facetResults"))) { #optional property not found
            $FacetResults = $null
        } else {
            $FacetResults = $JsonParameters.PSobject.Properties["facetResults"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "resultTabs"))) { #optional property not found
            $ResultTabs = $null
        } else {
            $ResultTabs = $JsonParameters.PSobject.Properties["resultTabs"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "resultTabIds"))) { #optional property not found
            $ResultTabIds = $null
        } else {
            $ResultTabIds = $JsonParameters.PSobject.Properties["resultTabIds"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "resultsDescription"))) { #optional property not found
            $ResultsDescription = $null
        } else {
            $ResultsDescription = $JsonParameters.PSobject.Properties["resultsDescription"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "rewrittenFacetFilters"))) { #optional property not found
            $RewrittenFacetFilters = $null
        } else {
            $RewrittenFacetFilters = $JsonParameters.PSobject.Properties["rewrittenFacetFilters"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "cursor"))) { #optional property not found
            $Cursor = $null
        } else {
            $Cursor = $JsonParameters.PSobject.Properties["cursor"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "hasMoreResults"))) { #optional property not found
            $HasMoreResults = $null
        } else {
            $HasMoreResults = $JsonParameters.PSobject.Properties["hasMoreResults"].value
        }

        $PSO = [PSCustomObject]@{
            "trackingToken" = ${TrackingToken}
            "sessionInfo" = ${SessionInfo}
            "results" = ${Results}
            "structuredResults" = ${StructuredResults}
            "generatedQnaResult" = ${GeneratedQnaResult}
            "errorInfo" = ${ErrorInfo}
            "requestID" = ${RequestID}
            "backendTimeMillis" = ${BackendTimeMillis}
            "experimentIds" = ${ExperimentIds}
            "metadata" = ${Metadata}
            "facetResults" = ${FacetResults}
            "resultTabs" = ${ResultTabs}
            "resultTabIds" = ${ResultTabIds}
            "resultsDescription" = ${ResultsDescription}
            "rewrittenFacetFilters" = ${RewrittenFacetFilters}
            "cursor" = ${Cursor}
            "hasMoreResults" = ${HasMoreResults}
        }

        return $PSO
    }

}

