#
# Glean Client API
# # Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 
# Version: 0.9.0
# Contact: support@glean.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER RewrittenQuery
A cleaned up or updated version of the query to be displayed in the query box. Useful for mapping visual facets to search operators.
.PARAMETER SearchedQuery
The actual query used to perform search and return results.
.PARAMETER SearchedQueryRanges
The bolded ranges within the searched query.
.PARAMETER OriginalQuery
The query text sent by the client in the request.
.PARAMETER QuerySuggestion
No description available.
.PARAMETER AdditionalQuerySuggestions
No description available.
.PARAMETER NegatedTerms
A list of terms that were negated when processing the query.
.PARAMETER ModifiedQueryWasUsed
A different query was performed than the one requested.
.PARAMETER OriginalQueryHadNoResults
No results were found for the original query. The usage of this bit in conjunction with modifiedQueryWasUsed will dictate whether the full page replacement is 0-result or few-result based.
.PARAMETER SearchWarning
No description available.
.PARAMETER TriggeredExpertDetection
Whether the query triggered expert detection results in the People tab.
.OUTPUTS

SearchResponseMetadata<PSCustomObject>
#>

function Initialize-SearchResponseMetadata {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${RewrittenQuery},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${SearchedQuery},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${SearchedQueryRanges},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${OriginalQuery},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${QuerySuggestion},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${AdditionalQuerySuggestions},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${NegatedTerms},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${ModifiedQueryWasUsed},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${OriginalQueryHadNoResults},
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${SearchWarning},
        [Parameter(Position = 10, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${TriggeredExpertDetection}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => SearchResponseMetadata' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "rewrittenQuery" = ${RewrittenQuery}
            "searchedQuery" = ${SearchedQuery}
            "searchedQueryRanges" = ${SearchedQueryRanges}
            "originalQuery" = ${OriginalQuery}
            "querySuggestion" = ${QuerySuggestion}
            "additionalQuerySuggestions" = ${AdditionalQuerySuggestions}
            "negatedTerms" = ${NegatedTerms}
            "modifiedQueryWasUsed" = ${ModifiedQueryWasUsed}
            "originalQueryHadNoResults" = ${OriginalQueryHadNoResults}
            "searchWarning" = ${SearchWarning}
            "triggeredExpertDetection" = ${TriggeredExpertDetection}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to SearchResponseMetadata<PSCustomObject>

.DESCRIPTION

Convert from JSON to SearchResponseMetadata<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

SearchResponseMetadata<PSCustomObject>
#>
function ConvertFrom-JsonToSearchResponseMetadata {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => SearchResponseMetadata' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in SearchResponseMetadata
        $AllProperties = ("rewrittenQuery", "searchedQuery", "searchedQueryRanges", "originalQuery", "querySuggestion", "additionalQuerySuggestions", "negatedTerms", "modifiedQueryWasUsed", "originalQueryHadNoResults", "searchWarning", "triggeredExpertDetection")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "rewrittenQuery"))) { #optional property not found
            $RewrittenQuery = $null
        } else {
            $RewrittenQuery = $JsonParameters.PSobject.Properties["rewrittenQuery"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "searchedQuery"))) { #optional property not found
            $SearchedQuery = $null
        } else {
            $SearchedQuery = $JsonParameters.PSobject.Properties["searchedQuery"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "searchedQueryRanges"))) { #optional property not found
            $SearchedQueryRanges = $null
        } else {
            $SearchedQueryRanges = $JsonParameters.PSobject.Properties["searchedQueryRanges"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "originalQuery"))) { #optional property not found
            $OriginalQuery = $null
        } else {
            $OriginalQuery = $JsonParameters.PSobject.Properties["originalQuery"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "querySuggestion"))) { #optional property not found
            $QuerySuggestion = $null
        } else {
            $QuerySuggestion = $JsonParameters.PSobject.Properties["querySuggestion"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "additionalQuerySuggestions"))) { #optional property not found
            $AdditionalQuerySuggestions = $null
        } else {
            $AdditionalQuerySuggestions = $JsonParameters.PSobject.Properties["additionalQuerySuggestions"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "negatedTerms"))) { #optional property not found
            $NegatedTerms = $null
        } else {
            $NegatedTerms = $JsonParameters.PSobject.Properties["negatedTerms"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "modifiedQueryWasUsed"))) { #optional property not found
            $ModifiedQueryWasUsed = $null
        } else {
            $ModifiedQueryWasUsed = $JsonParameters.PSobject.Properties["modifiedQueryWasUsed"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "originalQueryHadNoResults"))) { #optional property not found
            $OriginalQueryHadNoResults = $null
        } else {
            $OriginalQueryHadNoResults = $JsonParameters.PSobject.Properties["originalQueryHadNoResults"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "searchWarning"))) { #optional property not found
            $SearchWarning = $null
        } else {
            $SearchWarning = $JsonParameters.PSobject.Properties["searchWarning"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "triggeredExpertDetection"))) { #optional property not found
            $TriggeredExpertDetection = $null
        } else {
            $TriggeredExpertDetection = $JsonParameters.PSobject.Properties["triggeredExpertDetection"].value
        }

        $PSO = [PSCustomObject]@{
            "rewrittenQuery" = ${RewrittenQuery}
            "searchedQuery" = ${SearchedQuery}
            "searchedQueryRanges" = ${SearchedQueryRanges}
            "originalQuery" = ${OriginalQuery}
            "querySuggestion" = ${QuerySuggestion}
            "additionalQuerySuggestions" = ${AdditionalQuerySuggestions}
            "negatedTerms" = ${NegatedTerms}
            "modifiedQueryWasUsed" = ${ModifiedQueryWasUsed}
            "originalQueryHadNoResults" = ${OriginalQueryHadNoResults}
            "searchWarning" = ${SearchWarning}
            "triggeredExpertDetection" = ${TriggeredExpertDetection}
        }

        return $PSO
    }

}

