#
# Glean Client API
# # Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 
# Version: 0.9.0
# Contact: support@glean.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER LastLogTimestamp
Unix timestamp of the last activity processed to make the response (in seconds since epoch UTC).
.PARAMETER ShortcutInsights
Insights for shortcuts.
.PARAMETER Departments
list of departments applicable for shortcuts tab.
.PARAMETER MinVisitorThreshold
Min threshold in number of visitors while populating results, otherwise 0.
.OUTPUTS

ShortcutInsightsResponse<PSCustomObject>
#>

function Initialize-ShortcutInsightsResponse {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${LastLogTimestamp},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${ShortcutInsights},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${Departments},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${MinVisitorThreshold}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => ShortcutInsightsResponse' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "lastLogTimestamp" = ${LastLogTimestamp}
            "shortcutInsights" = ${ShortcutInsights}
            "departments" = ${Departments}
            "minVisitorThreshold" = ${MinVisitorThreshold}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ShortcutInsightsResponse<PSCustomObject>

.DESCRIPTION

Convert from JSON to ShortcutInsightsResponse<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ShortcutInsightsResponse<PSCustomObject>
#>
function ConvertFrom-JsonToShortcutInsightsResponse {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => ShortcutInsightsResponse' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in ShortcutInsightsResponse
        $AllProperties = ("lastLogTimestamp", "shortcutInsights", "departments", "minVisitorThreshold")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "lastLogTimestamp"))) { #optional property not found
            $LastLogTimestamp = $null
        } else {
            $LastLogTimestamp = $JsonParameters.PSobject.Properties["lastLogTimestamp"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "shortcutInsights"))) { #optional property not found
            $ShortcutInsights = $null
        } else {
            $ShortcutInsights = $JsonParameters.PSobject.Properties["shortcutInsights"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "departments"))) { #optional property not found
            $Departments = $null
        } else {
            $Departments = $JsonParameters.PSobject.Properties["departments"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "minVisitorThreshold"))) { #optional property not found
            $MinVisitorThreshold = $null
        } else {
            $MinVisitorThreshold = $JsonParameters.PSobject.Properties["minVisitorThreshold"].value
        }

        $PSO = [PSCustomObject]@{
            "lastLogTimestamp" = ${LastLogTimestamp}
            "shortcutInsights" = ${ShortcutInsights}
            "departments" = ${Departments}
            "minVisitorThreshold" = ${MinVisitorThreshold}
        }

        return $PSO
    }

}

