#
# Glean Client API
# # Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 
# Version: 0.9.0
# Contact: support@glean.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

A single object that can support any object in the work graph. Only a single object will be populated.

.PARAMETER Document
No description available.
.PARAMETER Person
No description available.
.PARAMETER Customer
No description available.
.PARAMETER Team
No description available.
.PARAMETER CustomEntity
No description available.
.PARAMETER Answer
No description available.
.PARAMETER ExtractedQnA
No description available.
.PARAMETER App
No description available.
.PARAMETER Collection
No description available.
.PARAMETER AnswerBoard
No description available.
.PARAMETER Code
No description available.
.PARAMETER Shortcut
No description available.
.PARAMETER QuerySuggestions
No description available.
.PARAMETER RelatedDocuments
A list of documents related to this structured result.
.PARAMETER RelatedQuestion
No description available.
.PARAMETER Snippets
Any snippets associated to the populated object.
.PARAMETER TrackingToken
An opaque token that represents this particular result in this particular query. To be used for /feedback reporting.
.PARAMETER Prominence
The level of visual distinction that should be given to a result.
.PARAMETER Source
Source context for this result. Possible values depend on the result type.
.OUTPUTS

StructuredResult<PSCustomObject>
#>

function Initialize-StructuredResult {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Document},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Person},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Customer},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Team},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${CustomEntity},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Answer},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${ExtractedQnA},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${App},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Collection},
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${AnswerBoard},
        [Parameter(Position = 10, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Code},
        [Parameter(Position = 11, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Shortcut},
        [Parameter(Position = 12, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${QuerySuggestions},
        [Parameter(Position = 13, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${RelatedDocuments},
        [Parameter(Position = 14, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${RelatedQuestion},
        [Parameter(Position = 15, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Snippets},
        [Parameter(Position = 16, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${TrackingToken},
        [Parameter(Position = 17, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("HERO", "PROMOTED", "STANDARD")]
        [String]
        ${Prominence},
        [Parameter(Position = 18, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("EXPERT_DETECTION", "ENTITY_NLQ")]
        [String]
        ${Source}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => StructuredResult' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "document" = ${Document}
            "person" = ${Person}
            "customer" = ${Customer}
            "team" = ${Team}
            "customEntity" = ${CustomEntity}
            "answer" = ${Answer}
            "extractedQnA" = ${ExtractedQnA}
            "app" = ${App}
            "collection" = ${Collection}
            "answerBoard" = ${AnswerBoard}
            "code" = ${Code}
            "shortcut" = ${Shortcut}
            "querySuggestions" = ${QuerySuggestions}
            "relatedDocuments" = ${RelatedDocuments}
            "relatedQuestion" = ${RelatedQuestion}
            "snippets" = ${Snippets}
            "trackingToken" = ${TrackingToken}
            "prominence" = ${Prominence}
            "source" = ${Source}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to StructuredResult<PSCustomObject>

.DESCRIPTION

Convert from JSON to StructuredResult<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

StructuredResult<PSCustomObject>
#>
function ConvertFrom-JsonToStructuredResult {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => StructuredResult' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in StructuredResult
        $AllProperties = ("document", "person", "customer", "team", "customEntity", "answer", "extractedQnA", "app", "collection", "answerBoard", "code", "shortcut", "querySuggestions", "relatedDocuments", "relatedQuestion", "snippets", "trackingToken", "prominence", "source")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "document"))) { #optional property not found
            $Document = $null
        } else {
            $Document = $JsonParameters.PSobject.Properties["document"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "person"))) { #optional property not found
            $Person = $null
        } else {
            $Person = $JsonParameters.PSobject.Properties["person"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "customer"))) { #optional property not found
            $Customer = $null
        } else {
            $Customer = $JsonParameters.PSobject.Properties["customer"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "team"))) { #optional property not found
            $Team = $null
        } else {
            $Team = $JsonParameters.PSobject.Properties["team"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "customEntity"))) { #optional property not found
            $CustomEntity = $null
        } else {
            $CustomEntity = $JsonParameters.PSobject.Properties["customEntity"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "answer"))) { #optional property not found
            $Answer = $null
        } else {
            $Answer = $JsonParameters.PSobject.Properties["answer"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "extractedQnA"))) { #optional property not found
            $ExtractedQnA = $null
        } else {
            $ExtractedQnA = $JsonParameters.PSobject.Properties["extractedQnA"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "app"))) { #optional property not found
            $App = $null
        } else {
            $App = $JsonParameters.PSobject.Properties["app"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "collection"))) { #optional property not found
            $Collection = $null
        } else {
            $Collection = $JsonParameters.PSobject.Properties["collection"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "answerBoard"))) { #optional property not found
            $AnswerBoard = $null
        } else {
            $AnswerBoard = $JsonParameters.PSobject.Properties["answerBoard"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "code"))) { #optional property not found
            $Code = $null
        } else {
            $Code = $JsonParameters.PSobject.Properties["code"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "shortcut"))) { #optional property not found
            $Shortcut = $null
        } else {
            $Shortcut = $JsonParameters.PSobject.Properties["shortcut"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "querySuggestions"))) { #optional property not found
            $QuerySuggestions = $null
        } else {
            $QuerySuggestions = $JsonParameters.PSobject.Properties["querySuggestions"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "relatedDocuments"))) { #optional property not found
            $RelatedDocuments = $null
        } else {
            $RelatedDocuments = $JsonParameters.PSobject.Properties["relatedDocuments"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "relatedQuestion"))) { #optional property not found
            $RelatedQuestion = $null
        } else {
            $RelatedQuestion = $JsonParameters.PSobject.Properties["relatedQuestion"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "snippets"))) { #optional property not found
            $Snippets = $null
        } else {
            $Snippets = $JsonParameters.PSobject.Properties["snippets"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "trackingToken"))) { #optional property not found
            $TrackingToken = $null
        } else {
            $TrackingToken = $JsonParameters.PSobject.Properties["trackingToken"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "prominence"))) { #optional property not found
            $Prominence = $null
        } else {
            $Prominence = $JsonParameters.PSobject.Properties["prominence"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "source"))) { #optional property not found
            $Source = $null
        } else {
            $Source = $JsonParameters.PSobject.Properties["source"].value
        }

        $PSO = [PSCustomObject]@{
            "document" = ${Document}
            "person" = ${Person}
            "customer" = ${Customer}
            "team" = ${Team}
            "customEntity" = ${CustomEntity}
            "answer" = ${Answer}
            "extractedQnA" = ${ExtractedQnA}
            "app" = ${App}
            "collection" = ${Collection}
            "answerBoard" = ${AnswerBoard}
            "code" = ${Code}
            "shortcut" = ${Shortcut}
            "querySuggestions" = ${QuerySuggestions}
            "relatedDocuments" = ${RelatedDocuments}
            "relatedQuestion" = ${RelatedQuestion}
            "snippets" = ${Snippets}
            "trackingToken" = ${TrackingToken}
            "prominence" = ${Prominence}
            "source" = ${Source}
        }

        return $PSO
    }

}

