#
# Glean Client API
# # Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 
# Version: 0.9.0
# Contact: support@glean.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

A set of Theme objects to make available to the user based on their chosen preference. If a theme variant is not supplied, the default theme will be used.

.PARAMETER Light
A map of {string, string} pairs where the key represents a known theme option and the value is the CSS color to apply. Supported options are documented in https://dev.glean.com/meta/browser_api/interfaces/Theme.html.
.PARAMETER Dark
A map of {string, string} pairs where the key represents a known theme option and the value is the CSS color to apply. Supported options are documented in https://dev.glean.com/meta/browser_api/interfaces/Theme.html.
.OUTPUTS

Themes<PSCustomObject>
#>

function Initialize-Themes {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Collections.Hashtable]
        ${Light},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Collections.Hashtable]
        ${Dark}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => Themes' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "light" = ${Light}
            "dark" = ${Dark}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to Themes<PSCustomObject>

.DESCRIPTION

Convert from JSON to Themes<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

Themes<PSCustomObject>
#>
function ConvertFrom-JsonToThemes {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => Themes' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in Themes
        $AllProperties = ("light", "dark")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "light"))) { #optional property not found
            $Light = $null
        } else {
            $Light = $JsonParameters.PSobject.Properties["light"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "dark"))) { #optional property not found
            $Dark = $null
        } else {
            $Dark = $JsonParameters.PSobject.Properties["dark"].value
        }

        $PSO = [PSCustomObject]@{
            "light" = ${Light}
            "dark" = ${Dark}
        }

        return $PSO
    }

}

