#
# Glean Client API
# # Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 
# Version: 0.9.0
# Contact: support@glean.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER LastLogTimestamp
Unix timestamp of the last activity processed to make the response (in seconds since epoch UTC).
.PARAMETER ActivityInsights
Insights for all active users with respect to set of actions.
.PARAMETER InactiveInsights
Insights for all in inactive users with respect to set of actions and time period. Activity count will be set to 0.
.PARAMETER TotalTeammates
Total number of teammates that have logged in to the product, that are still valid teammates.
.PARAMETER TotalActiveUsers
Total number of active users in the requested period.
.PARAMETER Departments
list of departments applicable for users tab.
.OUTPUTS

UserInsightsResponse<PSCustomObject>
#>

function Initialize-UserInsightsResponse {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${LastLogTimestamp},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${ActivityInsights},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${InactiveInsights},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${TotalTeammates},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${TotalActiveUsers},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${Departments}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => UserInsightsResponse' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "lastLogTimestamp" = ${LastLogTimestamp}
            "activityInsights" = ${ActivityInsights}
            "inactiveInsights" = ${InactiveInsights}
            "totalTeammates" = ${TotalTeammates}
            "totalActiveUsers" = ${TotalActiveUsers}
            "departments" = ${Departments}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to UserInsightsResponse<PSCustomObject>

.DESCRIPTION

Convert from JSON to UserInsightsResponse<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

UserInsightsResponse<PSCustomObject>
#>
function ConvertFrom-JsonToUserInsightsResponse {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => UserInsightsResponse' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in UserInsightsResponse
        $AllProperties = ("lastLogTimestamp", "activityInsights", "inactiveInsights", "totalTeammates", "totalActiveUsers", "departments")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "lastLogTimestamp"))) { #optional property not found
            $LastLogTimestamp = $null
        } else {
            $LastLogTimestamp = $JsonParameters.PSobject.Properties["lastLogTimestamp"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "activityInsights"))) { #optional property not found
            $ActivityInsights = $null
        } else {
            $ActivityInsights = $JsonParameters.PSobject.Properties["activityInsights"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "inactiveInsights"))) { #optional property not found
            $InactiveInsights = $null
        } else {
            $InactiveInsights = $JsonParameters.PSobject.Properties["inactiveInsights"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "totalTeammates"))) { #optional property not found
            $TotalTeammates = $null
        } else {
            $TotalTeammates = $JsonParameters.PSobject.Properties["totalTeammates"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "totalActiveUsers"))) { #optional property not found
            $TotalActiveUsers = $null
        } else {
            $TotalActiveUsers = $JsonParameters.PSobject.Properties["totalActiveUsers"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "departments"))) { #optional property not found
            $Departments = $null
        } else {
            $Departments = $JsonParameters.PSobject.Properties["departments"].value
        }

        $PSO = [PSCustomObject]@{
            "lastLogTimestamp" = ${LastLogTimestamp}
            "activityInsights" = ${ActivityInsights}
            "inactiveInsights" = ${InactiveInsights}
            "totalTeammates" = ${TotalTeammates}
            "totalActiveUsers" = ${TotalActiveUsers}
            "departments" = ${Departments}
        }

        return $PSO
    }

}

