#
# Glean Client API
# # Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 
# Version: 0.9.0
# Contact: support@glean.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Actor
No description available.
.PARAMETER Timestamp
Unix timestamp of the activity (in seconds since epoch UTC).
.PARAMETER Action
The action for the activity
.PARAMETER AggregateVisitCount
No description available.
.OUTPUTS

UserActivity<PSCustomObject>
#>

function Initialize-UserActivity {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Actor},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Timestamp},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("ADD", "ADD_REMINDER", "CLICK", "COMMENT", "DELETE", "DISMISS", "EDIT", "MENTION", "MOVE", "OTHER", "RESTORE", "UNKNOWN", "VERIFY", "VIEW")]
        [String]
        ${Action},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${AggregateVisitCount}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => UserActivity' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "actor" = ${Actor}
            "timestamp" = ${Timestamp}
            "action" = ${Action}
            "aggregateVisitCount" = ${AggregateVisitCount}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to UserActivity<PSCustomObject>

.DESCRIPTION

Convert from JSON to UserActivity<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

UserActivity<PSCustomObject>
#>
function ConvertFrom-JsonToUserActivity {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => UserActivity' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in UserActivity
        $AllProperties = ("actor", "timestamp", "action", "aggregateVisitCount")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "actor"))) { #optional property not found
            $Actor = $null
        } else {
            $Actor = $JsonParameters.PSobject.Properties["actor"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "timestamp"))) { #optional property not found
            $Timestamp = $null
        } else {
            $Timestamp = $JsonParameters.PSobject.Properties["timestamp"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "action"))) { #optional property not found
            $Action = $null
        } else {
            $Action = $JsonParameters.PSobject.Properties["action"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "aggregateVisitCount"))) { #optional property not found
            $AggregateVisitCount = $null
        } else {
            $AggregateVisitCount = $JsonParameters.PSobject.Properties["aggregateVisitCount"].value
        }

        $PSO = [PSCustomObject]@{
            "actor" = ${Actor}
            "timestamp" = ${Timestamp}
            "action" = ${Action}
            "aggregateVisitCount" = ${AggregateVisitCount}
        }

        return $PSO
    }

}

