#
# Glean Client API
# # Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 
# Version: 0.9.0
# Contact: support@glean.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER WeeklyFeedEmailEnabled
Whether the weekly feed email is enabled
.PARAMETER OnboardingCampaignEnabled
Whether the onboarding email campaign is enabled
.OUTPUTS

UserOutreachConfig<PSCustomObject>
#>

function Initialize-UserOutreachConfig {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${WeeklyFeedEmailEnabled},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${OnboardingCampaignEnabled}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => UserOutreachConfig' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "weeklyFeedEmailEnabled" = ${WeeklyFeedEmailEnabled}
            "onboardingCampaignEnabled" = ${OnboardingCampaignEnabled}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to UserOutreachConfig<PSCustomObject>

.DESCRIPTION

Convert from JSON to UserOutreachConfig<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

UserOutreachConfig<PSCustomObject>
#>
function ConvertFrom-JsonToUserOutreachConfig {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => UserOutreachConfig' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in UserOutreachConfig
        $AllProperties = ("weeklyFeedEmailEnabled", "onboardingCampaignEnabled")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "weeklyFeedEmailEnabled"))) { #optional property not found
            $WeeklyFeedEmailEnabled = $null
        } else {
            $WeeklyFeedEmailEnabled = $JsonParameters.PSobject.Properties["weeklyFeedEmailEnabled"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "onboardingCampaignEnabled"))) { #optional property not found
            $OnboardingCampaignEnabled = $null
        } else {
            $OnboardingCampaignEnabled = $JsonParameters.PSobject.Properties["onboardingCampaignEnabled"].value
        }

        $PSO = [PSCustomObject]@{
            "weeklyFeedEmailEnabled" = ${WeeklyFeedEmailEnabled}
            "onboardingCampaignEnabled" = ${OnboardingCampaignEnabled}
        }

        return $PSO
    }

}

