#
# Glean Client API
# # Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 
# Version: 0.9.0
# Contact: support@glean.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Describes the write permissions levels that a user has for a specific feature

.PARAMETER ScopeType
No description available.
.PARAMETER Create
True if user has create permission for this feature and scope
.PARAMETER Update
True if user has update permission for this feature and scope
.PARAMETER Delete
True if user has delete permission for this feature and scope
.OUTPUTS

WritePermission<PSCustomObject>
#>

function Initialize-WritePermission {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("GLOBAL", "OWN")]
        [PSCustomObject]
        ${ScopeType},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${Create},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${Update},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${Delete}
    )

    Process {
        'Creating PSCustomObject: PSOpenAPITools => WritePermission' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "scopeType" = ${ScopeType}
            "create" = ${Create}
            "update" = ${Update}
            "delete" = ${Delete}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to WritePermission<PSCustomObject>

.DESCRIPTION

Convert from JSON to WritePermission<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

WritePermission<PSCustomObject>
#>
function ConvertFrom-JsonToWritePermission {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSOpenAPITools => WritePermission' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in WritePermission
        $AllProperties = ("scopeType", "create", "update", "delete")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "scopeType"))) { #optional property not found
            $ScopeType = $null
        } else {
            $ScopeType = $JsonParameters.PSobject.Properties["scopeType"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "create"))) { #optional property not found
            $Create = $null
        } else {
            $Create = $JsonParameters.PSobject.Properties["create"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "update"))) { #optional property not found
            $Update = $null
        } else {
            $Update = $JsonParameters.PSobject.Properties["update"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "delete"))) { #optional property not found
            $Delete = $null
        } else {
            $Delete = $JsonParameters.PSobject.Properties["delete"].value
        }

        $PSO = [PSCustomObject]@{
            "scopeType" = ${ScopeType}
            "create" = ${Create}
            "update" = ${Update}
            "delete" = ${Delete}
        }

        return $PSO
    }

}

