#
# Glean Client API
# # Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 
# Version: 0.9.0
# Contact: support@glean.com
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSOpenAPITools' -name 'PersonMetadata' {
    Context 'PersonMetadata' {
        It 'Initialize-PersonMetadata' {
            # a simple test to create an object
            #$NewObject = Initialize-PersonMetadata -Type "TEST_VALUE" -FirstName "TEST_VALUE" -LastName "TEST_VALUE" -Title "TEST_VALUE" -BusinessUnit "TEST_VALUE" -Department "TEST_VALUE" -Teams "TEST_VALUE" -DepartmentCount "TEST_VALUE" -Email "TEST_VALUE" -AliasEmails "TEST_VALUE" -Location "TEST_VALUE" -StructuredLocation "TEST_VALUE" -ExternalProfileLink "TEST_VALUE" -Manager "TEST_VALUE" -ManagementChain "TEST_VALUE" -Phone "TEST_VALUE" -Timezone "TEST_VALUE" -TimezoneOffset "TEST_VALUE" -PhotoUrl "TEST_VALUE" -UneditedPhotoUrl "TEST_VALUE" -BannerUrl "TEST_VALUE" -Reports "TEST_VALUE" -StartDate "TEST_VALUE" -EndDate "TEST_VALUE" -Bio "TEST_VALUE" -Pronoun "TEST_VALUE" -OrgSizeCount "TEST_VALUE" -DirectReportsCount "TEST_VALUE" -PreferredName "TEST_VALUE" -SocialNetwork "TEST_VALUE" -DatasourceProfile "TEST_VALUE" -QuerySuggestions "TEST_VALUE" -PeopleDistance "TEST_VALUE" -InviteInfo "TEST_VALUE" -IsSignedUp "TEST_VALUE" -LastExtensionUse "TEST_VALUE" -Permissions "TEST_VALUE" -CustomFields "TEST_VALUE" -LoggingId "TEST_VALUE" -StartDatePercentile "TEST_VALUE" -BusyEvents "TEST_VALUE" -ProfileBoolSettings "TEST_VALUE" -Badges "TEST_VALUE" -IsOrgRoot "TEST_VALUE"
            #$NewObject | Should -BeOfType PersonMetadata
            #$NewObject.property | Should -Be 0
        }
    }
}
